export const streamsMock = [
    {
        sportDisplayOrder: '75',
        sportEventId: '299248',
        externalId: 'esports:match:c9f088bc-2b7a-4921-aad3-8f88697a6d6b',
        name: 'G2 Esports vs M80',
        competitionDisplayOrder: '0',
        sportId: 'csgo',
        provider: 'bayes',
        eventStartTime: '2024-04-26T11:30:00.000Z',
        id: 'bc657927-7405-4e74-b408-c805db4dc7e6',
    },
    {
        sportDisplayOrder: '75',
        sportEventId: '299257',
        externalId: 'esports:match:ed9b4d16-b58d-4c4d-b2fb-44a88a090ce8',
        name: 'Betboom Team vs Team Falcons',
        competitionDisplayOrder: '0',
        sportId: 'csgo',
        provider: 'bayes',
        eventStartTime: '2024-04-26T11:30:00.000Z',
        id: '91187508-6536-4637-94dc-32dff1501db6',
    },
    {
        sportDisplayOrder: '96',
        sportEventId: '281160',
        externalId: 'av:stream:15308975',
        name: 'Etcheverry, Tomas Martin vs Shapovalov, Denis',
        competitionDisplayOrder: '0',
        sportId: 'tennis',
        provider: 'bet-radar',
        eventStartTime: '2024-04-26T11:40:00.000Z',
        id: 'c3ea13ef-af36-49fa-8823-84a0011d5a22',
    },
    {
        sportDisplayOrder: '96',
        sportEventId: '283263',
        externalId: 'av:stream:15420435',
        name: 'Travaglia, Stefano vs Maestrelli, Francesco',
        competitionDisplayOrder: '0',
        sportId: 'tennis',
        provider: 'bet-radar',
        eventStartTime: '2024-04-26T10:40:00.000Z',
        id: '661ff680-9259-4935-b195-eab903e7abf9',
    },
    {
        sportDisplayOrder: '98',
        sportEventId: '297320',
        externalId: '17646492-300-26A864C590529D0F575810D17FA6C4EB',
        name: 'Bank of Taiwan vs Yulon Dinos',
        competitionDisplayOrder: '99989',
        sportId: 'basketball',
        provider: 'g-live',
        eventStartTime: '2024-04-26T11:00:00.000Z',
        id: 'd22c8ea6-0b36-4382-96de-4487af885220',
    },
    {
        sportDisplayOrder: '100',
        sportEventId: '295224',
        externalId: '17645005-755-BF8E4393D0F297A12677F88AAC1321DE',
        name: 'Rans Nusantara vs Persija Jakarta',
        competitionDisplayOrder: '99968',
        sportId: 'football',
        provider: 'g-live',
        eventStartTime: '2024-04-26T12:00:00.000Z',
        id: '013cdee2-40d1-4c6e-86f0-b759168abf38',
    },
    {
        sportDisplayOrder: '100',
        sportEventId: '139590',
        externalId: '10862670',
        name: 'Wuhan Three Towns FC vs Tianjin Teda',
        competitionDisplayOrder: '99236',
        sportId: 'football',
        provider: 'bet-genius',
        eventStartTime: '2024-04-26T11:35:00.000Z',
        id: '0b702452-2b1c-4f7f-b34b-6caadea344c2',
    },
    {
        sportDisplayOrder: '100',
        sportEventId: '139587',
        externalId: '10862668',
        name: 'Changchun Yatai vs Meizhou Hakka',
        competitionDisplayOrder: '99236',
        sportId: 'football',
        provider: 'bet-genius',
        eventStartTime: '2024-04-26T11:35:00.000Z',
        id: 'd715eb40-8ece-4404-a6ec-b2179eb6d587',
    },
    {
        sportDisplayOrder: '100',
        sportEventId: '139592',
        externalId: '10862669',
        name: 'Zhejiang FC vs Beijing Guoan',
        competitionDisplayOrder: '99236',
        sportId: 'football',
        provider: 'bet-genius',
        eventStartTime: '2024-04-26T11:35:00.000Z',
        id: '17f6fedd-f874-45a1-966b-f3b51c596b07',
    },
    {
        sportDisplayOrder: '98',
        sportEventId: '181964',
        externalId: '434475',
        name: 'Timplados Hotshots vs San Miguel Beermen',
        competitionDisplayOrder: '0',
        sportId: 'basketball',
        provider: 'img',
        eventStartTime: '2024-04-26T11:30:00.000Z',
        id: '6f7a1d18-07f8-4734-a45f-9825157cbc59',
    },
    {
        sportDisplayOrder: '100',
        sportEventId: '294524',
        externalId: '17644852-762-0212813A1AB20FF1AF15F1F6A3F3BAAE',
        name: 'AL Karkh vs Al Zawraa',
        competitionDisplayOrder: '0',
        sportId: 'football',
        provider: 'g-live',
        eventStartTime: '2024-04-26T12:45:00.000Z',
        id: '4da0fa3f-4449-40e7-a771-d559624aabbb',
    },
    {
        sportDisplayOrder: '100',
        sportEventId: '139595',
        externalId: '17636349-759-74CEB8B3AFF0CF4C03E58A4295D17269',
        name: 'Chengdu Rongcheng vs Shandong Luneng',
        competitionDisplayOrder: '99236',
        sportId: 'football',
        provider: 'g-live',
        eventStartTime: '2024-04-26T12:00:00.000Z',
        id: 'b6a73370-6ce1-46bc-b5f4-3533860f5fc5',
    },
    {
        sportDisplayOrder: '73',
        sportEventId: '297690',
        externalId: 'esports:match:db56a747-d18f-4419-ba0f-73779c4b342f',
        name: 'Team Liquid vs Heroic',
        competitionDisplayOrder: '0',
        sportId: 'dota2',
        provider: 'bayes',
        eventStartTime: '2024-04-26T11:00:00.000Z',
        id: '414bfd16-f6d9-48a3-9f73-8f0c00f9b95b',
    },
    {
        sportDisplayOrder: '98',
        sportEventId: '274524',
        externalId: '17647880-308-BE21BCDBFAE983DE13DED7FAB565438D',
        name: 'Guangzhou Loong Lions vs Xinjiang Flying Tigers',
        competitionDisplayOrder: '0',
        sportId: 'basketball',
        provider: 'g-live',
        eventStartTime: '2024-04-26T11:35:00.000Z',
        id: '8b40d9d9-5850-41f0-a786-d36d37624e8f',
    },
    {
        sportDisplayOrder: '96',
        sportEventId: '281138',
        externalId: 'av:stream:15309047',
        name: 'Baez, Sebastian vs van Assche, Luca',
        competitionDisplayOrder: '0',
        sportId: 'tennis',
        provider: 'bet-radar',
        eventStartTime: '2024-04-26T12:20:00.000Z',
        id: '58986cc0-67d9-4c93-9dac-4ea4c5153eae',
    },
    {
        sportDisplayOrder: '96',
        sportEventId: '283214',
        externalId: 'av:stream:15412549',
        name: 'Dzumhur, Damir vs Dalla Valle, Enrico',
        competitionDisplayOrder: '0',
        sportId: 'tennis',
        provider: 'bet-radar',
        eventStartTime: '2024-04-26T11:25:00.000Z',
        id: 'a3c98285-2492-4f75-bbf1-54db6ddacee9',
    },
    {
        sportDisplayOrder: '98',
        sportEventId: '279593',
        externalId: '17647881-310-180AB8A03D44DA885D81A7C55784C0FC',
        name: 'Shanghai Sharks vs Zhejiang Golden Bulls',
        competitionDisplayOrder: '0',
        sportId: 'basketball',
        provider: 'g-live',
        eventStartTime: '2024-04-26T11:35:00.000Z',
        id: 'd96264e3-ba48-4a7c-af97-56d182869544',
    },
    {
        name: 'FC Barcelona (Iron) vs Atletico Madrid (Donatello)',
        sportEventId: '297786',
        sportId: 'esoccer',
        sportDisplayOrder: '77',
        competitionDisplayOrder: '99998',
        streamId: '5df119a5-161e-4a3d-813e-0a1c10b5a7ef',
        provider: 'bet-radar',
    },
    {
        name: 'Hapoel Nof Hagalil FC vs Maccabi Herzliya',
        sportEventId: '296936',
        sportId: 'football',
        sportDisplayOrder: '100',
        competitionDisplayOrder: '99071',
        streamId: '57e2e949-dc62-4114-b83d-3a6b855fd23e',
        provider: 'g-live',
    },
    {
        name: 'Arsenal FC (Vangogh) vs SS Lazio (Arthur)',
        sportEventId: '297785',
        sportId: 'esoccer',
        sportDisplayOrder: '77',
        competitionDisplayOrder: '99998',
        streamId: '278f6924-ded3-4223-82e4-af52e0614a10',
        provider: 'bet-radar',
    },
    {
        name: 'Real Madrid (Aladdin) vs Manchester City FC (Magdy)',
        sportEventId: '298199',
        sportId: 'esoccer',
        sportDisplayOrder: '77',
        competitionDisplayOrder: '99999',
        streamId: '3d99e9d6-e4fc-4519-a217-8a93a95f2931',
        provider: 'bet-radar',
    },
    {
        name: 'FC Inter Milano (Panic) vs FC Bayern Munich (Nazario)',
        sportEventId: '298315',
        sportId: 'esoccer',
        sportDisplayOrder: '77',
        competitionDisplayOrder: '99999',
        streamId: '2183c640-d679-4037-92ea-9e8b2572953e',
        provider: 'bet-radar',
    },
    {
        name: 'Bayer 04 Leverkusen (Nio) vs Sporting CP (Aibothard)',
        sportEventId: '298294',
        sportId: 'esoccer',
        sportDisplayOrder: '77',
        competitionDisplayOrder: '99999',
        streamId: '7c86e2c8-744c-4ae8-8e30-23b36d6d7fb7',
        provider: 'bet-radar',
    },
    {
        name: 'Villarreal CF (Chemist) vs AS Roma (Cantona)',
        sportEventId: '298293',
        sportId: 'esoccer',
        sportDisplayOrder: '77',
        competitionDisplayOrder: '99999',
        streamId: '09e378e8-1b12-4845-9f37-3b9500a12250',
        provider: 'bet-radar',
    },
    {
        name: 'Bnei Yehuda Tel Aviv FC vs Hapoel Ironi Kiryat Shmona FC',
        sportEventId: '296918',
        sportId: 'football',
        sportDisplayOrder: '100',
        competitionDisplayOrder: '99071',
        streamId: 'fcbdc119-ed7e-4471-9782-cf55a9a17a96',
        provider: 'g-live',
    },
    {
        name: 'Jubb, Paul vs Peliwo, Filip',
        sportEventId: '298982',
        sportId: 'tennis',
        sportDisplayOrder: '96',
        competitionDisplayOrder: '0',
        streamId: 'ee3de97a-95d6-407b-9082-2448cfc0a794',
        provider: 'bet-radar',
    },
];

export const sportsMock = {
    americanfootball: {
        id: 'americanfootball',
        name: 'American Football',
        displayOrder: 97,
        tags: { 'skycity-events': ['-'], 'market-group': ['-'], category: ['-'], outright: ['no'], country: ['-'] },
    },
    badminton: {
        id: 'badminton',
        name: 'Badminton',
        displayOrder: 92,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['-'],
            category: ['-'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    baseball: {
        id: 'baseball',
        name: 'Baseball',
        displayOrder: 99,
        tags: { 'skycity-events': ['-'], 'market-group': ['Main'], category: ['-'], outright: ['no'], country: ['-'] },
    },
    basketball: {
        id: 'basketball',
        name: 'Basketball',
        displayOrder: 98,
        tags: {
            'skycity-events': ['-'],
            'overtime-length': ['5'],
            'market-group': ['-'],
            category: ['-'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
            'period-length': ['-'],
        },
    },
    beachvolleyball: {
        id: 'beachvolleyball',
        name: 'Beach volleyball',
        displayOrder: 93,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main', 'Handicaps', 'Totals', 'Point bets'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    boxing: {
        id: 'boxing',
        name: 'Boxing/MMA',
        displayOrder: 89,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main', 'Other'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    combatsports: {
        id: 'combatsports',
        name: 'Combat Sports',
        displayOrder: 80,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main', 'Other'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    csgo: { id: 'csgo', name: 'CS:GO', displayOrder: 75, tags: { 'market-group': [] } },
    darts: {
        id: 'darts',
        name: 'Darts',
        displayOrder: 88,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main', 'Handicaps', "180's", 'Totals', 'Set Betting'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    dota2: { id: 'dota2', name: 'Dota 2', displayOrder: 73, tags: { 'market-group': [] } },
    football: {
        id: 'football',
        name: 'Football',
        displayOrder: 100,
        tags: {
            'website-show': ['yes'],
            'skycity-events': ['-'],
            'market-group': ['main', 'test mg', 'asian', 'corners'],
            outright: ['no'],
            country: ['-'],
            region: ['-'],
            category: ['-'],
        },
    },
    formulaone: {
        id: 'formulaone',
        name: 'Formula One',
        displayOrder: 86,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main', 'Top Drivers', 'Head-to-head', 'Other/Specials', 'Outright'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    futsal: {
        id: 'futsal',
        name: 'Futsal',
        displayOrder: 85,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main', 'Handicap', 'Handicaps', 'Totals', 'Halves', 'Team', 'Race to', 'Other'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    golf: {
        id: 'golf',
        name: 'Golf',
        displayOrder: 87,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main', 'Special Bets', 'Outrights', 'Specials Bets'],
            'golf-tour': ['-'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    handball: {
        id: 'handball',
        name: 'Handball',
        displayOrder: 81,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main', 'Halves'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    icehockey: {
        id: 'icehockey',
        name: 'Ice Hockey',
        displayOrder: 94,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main', 'Periods', 'Game Props', 'Player Props'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    lol: { id: 'lol', name: 'League of Legends', displayOrder: 78, tags: { 'market-group': [] } },
    motorbikes: {
        id: 'motorbikes',
        name: 'Motorbikes',
        displayOrder: 84,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main', 'Outright'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    olympicgames: { id: 'olympicgames', name: 'Olympic Games', displayOrder: 79, tags: { 'market-group': [] } },
    rugbyleague: {
        id: 'rugbyleague',
        name: 'Rugby League',
        displayOrder: 83,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main', 'Halftime', 'Players'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    rugbyunion: {
        id: 'rugbyunion',
        name: 'Rugby Union',
        displayOrder: 82,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main', 'Halftime', 'Players'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    snooker: {
        id: 'snooker',
        name: 'Snooker',
        displayOrder: 90,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main', 'Frames', 'Breaks', 'Race to', 'Other'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    specials: { id: 'specials', name: 'Specials', displayOrder: 74, tags: { 'market-group': [] } },
    starcraft: { id: 'starcraft', name: 'StarCraft', displayOrder: 76, tags: { 'market-group': [] } },
    tabletennis: {
        id: 'tabletennis',
        name: 'Table Tennis',
        displayOrder: 91,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    tennis: {
        id: 'tennis',
        name: 'Tennis',
        displayOrder: 96,
        tags: {
            'tennis-tour': ['-'],
            'skycity-events': ['-'],
            'market-group': ['Main', 'Game Bets', 'Set Bets'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
    volleyball: {
        id: 'volleyball',
        name: 'Volleyball',
        displayOrder: 95,
        tags: {
            'skycity-events': ['-'],
            'market-group': ['Main'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
    },
};
