sonar.host.url=https://sonarcloud.io

sonar.projectName=sc-website
sonar.sources=./src,./src_server
sonar.organization=code-factory-group
sonar.projectKey=code-factory-group_sc-website
sonar.javascript.lcov.reportPaths=./reports/coverage-vitest/lcov.info
sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.exclusions=./src/styles-next/**, ./styles_backup/**, ./src_sassbuild/**, **/*.spec.ts, **/*.spec.tsx, **/*.test.ts, **/*.test.tsx, **/*.css, **/*.scss, **/node_modules/**
