export enum SubKey {
    event_card = 'event_card',
    event_row = 'event_row',
    outright_event = 'outright_event',
    selection_item = 'selection_item',
    av_event_row = 'av_event_row',
    event_marquee = 'marki_event',
    in_play_event = 'in_play_event',
    // markets
    av_eoc = 'av_eoc',
    av_eoc_line = 'av_eoc_line',
    esg = 'esg',
    event_card_mob = 'event_card_mob',
    correct_score = 'correct_score',
    outright_market = 'outright_market',
    suspended_market = 'suspend',
    market_marquee = 'marki_market',
    game_lines = 'game_lines',
    in_play_market = 'in_play_market',
    o_u_tmpl = 'o_u_tmpl',
    spread_tmpl = 'spread_tmpl',
    speed_bet_market = 'speed_bet',
    speed_bet_market_hidden = 'speed_bet_hidden',
    standard_bet = 'standard_bet',
    suspended_esg = 'suspended_esg',
    xbet_leg = 'xbet_leg',
    xbet_market = 'xbet_market',
    // used in test only
    test_bet = 'bet',
    test_event = 'test_event',
}
