import type { MyBet } from 'src/common/types/myBet';

export const openTabBets = [
    {
        legs: [
            {
                priceType: 'fp',
                price: {
                    d: 2.54,
                    f: '77/50',
                    fractionalNumerator: null,
                    fractionalDenominator: null,
                },
                spPrice: null,
                placeReduction: null,
                selection: {
                    id: 8663005,
                    name: 'Hapoel Umm AL Fahm',
                    metadata: {
                        nameTranslations: {
                            'ko-KR': '하포엘 움 알 파옴',
                        },
                    },
                },
                appliedInPlayDelay: 5,
                sport: {
                    id: 'football',
                    name: 'Football',
                },
                winReduction: null,
                eachWayTerms: null,
                inPlay: false,
                event: {
                    id: 24533,
                    name: 'Hapoel Umm AL Fahm vs Hapoel Rishon Lezion FC',
                    startTime: '2021-10-29T13:00:00Z',
                    statistics: {},
                    timeSettings: {
                        startTime: '2021-10-29T13:00:00.000Z',
                        timeZone: 'UTC',
                        started: false,
                        timeline: 'Prematch',
                        tradedInPlay: true,
                        offAtStartTime: false,
                    },
                },
                type: 'standard',
                id: '8663005',
                market: {
                    id: 3346738,
                    name: '1x2',
                    type: null,
                },
                result: null,
                competition: {
                    id: 89,
                    name: 'National League',
                },
            },
        ],
        settleType: null,
        potentialReturns: 1270000,
        payout: null,
        tax: null,
        betId: '402BI8BH7T',
        settledAt: null,
        affiliate: null,
        eachWay: false,
        placedAt: '2021-10-29T09:42:04Z',
        currency: 'KRW',
        status: 'open',
        totalStake: 500000,
        stakePerLine: 500000,
        numLines: 1,
        type: 'SGL',
        id: 'cf5de67b-1c63-4a73-a6f8-92f4a5192751',
        cashOut: false,
        cashout: {
            id: 'cf5de67b-1c63-4a73-a6f8-92f4a5192751',
            enabled: true,
            value: 461900,
        },
        balanceDelta: null,
        transaction: {
            id: null,
            type: null,
            status: null,
            currency: null,
            amount: null,
            totalAmount: null,
            assetFlows: [
                {
                    id: '86a87f07-eb93-4c0e-b2a3-5103cca76944',
                    date: '2021-10-29T09:42:04Z',
                    type: 'bet-placement',
                    balanceDelta: -500000,
                    balanceAfter: null,
                    currency: 'KRW',
                },
            ],
            tags: {
                selections: [8663005],
                freebetCredits: [],
                bonuses: [],
            },
        },
        comment: null,
    },
] as unknown as MyBet[];

export const liveTabBets = [
    {
        legs: [
            {
                priceType: 'fp',
                price: {
                    d: 2,
                    f: '1/1',
                    fractionalNumerator: null,
                    fractionalDenominator: null,
                },
                spPrice: null,
                placeReduction: null,
                selection: {
                    id: 9233887,
                    name: 'Dinamo Vladivostok (+9.5)',
                    metadata: {
                        nameTranslations: {
                            'ko-KR': '디나모 Vladivostok (+9.5)',
                        },
                    },
                },
                appliedInPlayDelay: 5,
                sport: {
                    id: 'basketball',
                    name: 'Basketball',
                },
                winReduction: null,
                eachWayTerms: null,
                inPlay: true,
                event: {
                    id: 24307,
                    name: 'Dinamo Vladivostok vs CSKA-2 Moscow',
                    startTime: '2021-10-29T09:10:00Z',
                    statistics: {
                        score: {
                            home: 18,
                            away: 31,
                        },
                        period: {
                            value: '2nd quarter',
                        },
                        timer: {
                            value: '5:20',
                        },
                    },
                    timeSettings: {
                        startTime: '2021-10-29T09:10:00.000Z',
                        timeZone: 'UTC',
                        started: true,
                        timeline: 'Started',
                        tradedInPlay: true,
                        offAtStartTime: false,
                    },
                },
                type: 'standard',
                id: '9233887',
                market: {
                    id: 3556808,
                    name: 'Handicap (incl. overtime)',
                    type: null,
                },
                result: null,
                competition: {
                    id: 362,
                    name: 'Superleague, 1st Division',
                },
            },
        ],
        settleType: null,
        potentialReturns: 1000000,
        payout: null,
        tax: null,
        betId: '402S47CFYH',
        settledAt: null,
        affiliate: null,
        eachWay: false,
        placedAt: '2021-10-29T09:20:53Z',
        currency: 'KRW',
        status: 'open',
        totalStake: 500000,
        stakePerLine: 500000,
        numLines: 1,
        type: 'SGL',
        id: 'd47551ce-f0f2-4ca3-9fee-55f20dd0ffb9',
        cashOut: false,
        cashout: {
            id: 'd47551ce-f0f2-4ca3-9fee-55f20dd0ffb9',
            enabled: false,
            value: 0,
        },
        balanceDelta: null,
        transaction: {
            id: null,
            type: null,
            status: null,
            currency: null,
            amount: null,
            totalAmount: null,
            assetFlows: [
                {
                    id: 'fede4c84-bfbd-40c4-aeb2-343f690a81f3',
                    date: '2021-10-29T09:20:53Z',
                    type: 'bet-placement',
                    balanceDelta: -500000,
                    balanceAfter: null,
                    currency: 'KRW',
                },
            ],
            tags: {
                selections: [9233887],
                freebetCredits: [],
                bonuses: [],
            },
        },
        comment: null,
    },
    {
        channel: 'desktop',
        legs: [
            {
                priceType: 'fp',
                termsWithBet: null,
                price: {
                    d: 2.54,
                    f: '77/50',
                },
                spPrice: null,
                selection: {
                    id: '8663005',
                    name: 'Hapoel Umm AL Fahm',
                    url: null,
                },
                feedProperties: {
                    eventId: 'sr:match:27772746',
                    marketId: '1',
                    selectionId: '1',
                    producerId: '3',
                    sportId: 'sr:sport:1',
                },
                problems: [],
                sport: {
                    id: 'football',
                    name: 'Football',
                    url: 'http://trading-api:8080/operator-sports/skycity/football',
                },
                eachWayTerms: null,
                inPlay: false,
                event: {
                    id: '24533',
                    name: 'Hapoel Umm AL Fahm vs Hapoel Rishon Lezion FC',
                    url: '',
                },
                type: 'standard',
                id: '8663005',
                market: {
                    id: '3346738',
                    name: '1x2',
                    url: '',
                },
                eventCountry: ['ISR'],
                result: null,
                competition: {
                    id: '89',
                    name: 'National League',
                    url: 'http://trading-api:8080/operator-competitions/skycity/89',
                },
            },
        ],
        freebet: false,
        potentialReturns: 1270000,
        payout: null,
        ip: '::1',
        stakeFactor: 1,
        operatorPayout: null,
        betId: '402BI8BH7T',
        settledAt: null,
        maxBet: 32467600,
        account: {
            id: 402,
            type: 'customer',
            name: 'cf onewallet',
        },
        eachWay: false,
        placedAt: '2021-10-29T09:42:04.000Z',
        settledBy: null,
        currency: 'KRW',
        status: 'open',
        remarks: [],
        placedBy: null,
        totalStake: 500000,
        country: 'GB',
        stakePerLine: 500000,
        numLines: 1,
        operatorTotalStake: 500000,
        type: 'SGL',
        operatorStakePerLine: 500000,
        id: 'cf5de67b-1c63-4a73-a6f8-92f4a5192751',
        cashOut: false,
        cashout: {
            id: 'cf5de67b-1c63-4a73-a6f8-92f4a5192751',
            enabled: true,
            value: 461900,
        },
        comment: null,
    },
] as unknown as MyBet[];

export const settledTabBets = [
    {
        id: 'ca9b61c1-a73f-414c-83fc-65d30e50591e',
        betId: '10063ZVCEB',
        type: 'SGL',
        status: 'settled',
        cashOut: false,
        eachWay: false,
        placedAt: '2022-10-12T08:13:04Z',
        settledAt: '2022-10-12T09:27:23Z',
        stakePerLine: 1000,
        totalStake: 1000,
        currency: 'GBP',
        payout: 1990,
        potentialReturns: 1990,
        balanceDelta: null,
        comment: null,
        settleType: 'selection',
        affiliate: null,
        transaction: {
            id: null,
            type: null,
            status: null,
            currency: null,
            amount: null,
            totalAmount: null,
            assetFlows: [
                {
                    id: 'a051ceaa-2e4d-4c8c-9000-9982e3b9b0d9',
                    date: '2022-10-12T08:13:04Z',
                    type: 'bet-placement',
                    balanceDelta: -1000,
                    balanceAfter: null,
                    currency: 'GBP',
                },
                {
                    id: 'b2e31c9e-66c5-463d-9441-2ccad326a0a9',
                    date: '2022-10-12T09:27:23Z',
                    type: 'bet-settlement',
                    balanceDelta: 1990,
                    balanceAfter: null,
                    currency: 'GBP',
                },
            ],
            tags: {
                selections: [16851035],
                freebetCredits: [],
                bonuses: [],
            },
        },
        numLines: 1,
        tax: null,
        legs: [
            {
                id: '16851035',
                type: 'standard',
                appliedInPlayDelay: 5,
                inPlay: true,
                priceType: 'fp',
                price: {
                    d: 1.99,
                    f: '99/100',
                    fractionalNumerator: null,
                    fractionalDenominator: null,
                },
                spPrice: null,
                winReduction: null,
                placeReduction: null,
                result: {
                    type: 'won',
                    place: null,
                    dividends: {
                        forecast: [],
                        tricast: [],
                    },
                    winReduction: null,
                    placeReduction: null,
                    r4Deductions: null,
                },
                eachWayTerms: null,
                sport: {
                    id: 'tennis',
                    name: 'Tennis',
                },
                competition: {
                    id: 1607,
                    name: 'ITF Greece F9, Men Singles',
                },
                event: {
                    id: 44273,
                    name: 'Roncalli, Simone vs Denisov, Ivan',
                    startTime: '2022-10-12T06:30:00Z',
                    statistics: {
                        'point-score': {
                            home: '',
                            away: '',
                        },
                        'set-score': {
                            home: 2,
                            away: 1,
                        },
                        'full-game-score': [
                            {
                                home: 6,
                                away: 3,
                            },
                            {
                                home: 3,
                                away: 6,
                            },
                            {
                                home: 6,
                                away: 1,
                            },
                        ],
                        'game-score': {
                            home: 6,
                            away: 1,
                        },
                        turn: {
                            value: '',
                        },
                        timer: {
                            value: '',
                        },
                        period: {
                            value: 'Ended',
                        },
                    },
                    timeSettings: {
                        startTime: '2022-10-12T06:30:00.000Z',
                        timeZone: 'UTC',
                        started: false,
                        timeline: 'Finished',
                        tradedInPlay: true,
                        offAtStartTime: false,
                    },
                },
                market: {
                    id: 6270461,
                    name: 'Total games',
                    type: null,
                },
                selection: {
                    id: 16851035,
                    name: 'over 19.5',
                    metadata: {
                        nameTranslations: {
                            'ko-KR': '오버 19.5',
                        },
                    },
                    line: null,
                },
                eventCountry: ['WRL'],
            },
        ],
    },
] as unknown as MyBet[];
