import {
    AllIcon,
    GlobeIcon,
    AmericanFootballIcon,
    BaseballIcon,
    BasketballIcon,
    BoxingMMAIcon,
    CombatSportsIcon,
    DartsIcon,
    FootballIcon,
    GolfIcon,
    HandballIcon,
    IceHockeyIcon,
    MotorbikesIcon,
    RugbyLeagueIcon,
    RugbyUnionIcon,
    SnookerIcon,
    TableTennisIcon,
    TennisIcon,
    VolleyballIcon,
    BadmintonIcon,
    BeachVolleyballIcon,
    FormulaOneIcon,
    FutsalIcon,
    SpecialsIcon,
    OlympicGamesIcon,
    StarCraftIcon,
    Dota2Icon,
    LeagueOfLegendsIcon,
    CSGOIcon,
    AustralianRulesIcon,
    CricketIcon,
    CyclingIcon,
    HorseracingIcon,
    MotorsportIcon,
    BiathlonIcon,
    CrosscountrySkiingIcon,
    NordiccombinedIcon,
    SkijumpingIcon,
} from '@solo-ui/sports-icons/svg';

import type { SportIcons } from './types';

export const SPORT_ICONS_SVG: SportIcons = {
    all: AllIcon,
    default: GlobeIcon,
    americanfootball: AmericanFootballIcon,
    australianrules: AustralianRulesIcon,
    baseball: BaseballIcon,
    basketball: BasketballIcon,
    boxing: BoxingMMAIcon,
    combatsports: CombatSportsIcon,
    cricket: CricketIcon,
    cycling: CyclingIcon,
    darts: DartsIcon,
    football: FootballIcon,
    golf: GolfIcon,
    handball: HandballIcon,
    horseracing: HorseracingIcon,
    icehockey: IceHockeyIcon,
    motorbikes: MotorbikesIcon,
    motorsport: MotorsportIcon,
    rugbyleague: RugbyLeagueIcon,
    rugbyunion: RugbyUnionIcon,
    snooker: SnookerIcon,
    tabletennis: TableTennisIcon,
    tennis: TennisIcon,
    biathlon: BiathlonIcon,
    crosscountryskiing: CrosscountrySkiingIcon,
    volleyball: VolleyballIcon,
    nordiccombined: NordiccombinedIcon,
    skijumping: SkijumpingIcon,
    badminton: BadmintonIcon,
    beachvolleyball: BeachVolleyballIcon,
    formulaone: FormulaOneIcon,
    futsal: FutsalIcon,
    specials: SpecialsIcon,
    olympicgames: OlympicGamesIcon,
    starcraft: StarCraftIcon,
    dota2: Dota2Icon,
    lol: LeagueOfLegendsIcon,
    csgo: CSGOIcon,
};