export const footballEvent = {
    id: 1,
    name: 'Liverpool vs Chelsea',
    originalName: 'Liverpool vs Chelsea',
    state: 'open',
    sport: 'football',
    competition: '1',
    template: 'match',
    eventType: null,
    displayOrder: 0,
    active: true,
    display: true,
    cashoutAvailable: false,
    blockSettlement: null,
    autoTakeDown: null,
    antePost: null,
    streams: [],
    tags: {
        'website-show': ['yes'],
        'market-group': ['-'],
        'country-label': ['England'],
        'speed-bet': ['no'],
        'asian-view': ['no'],
        highlight: ['no'],
        'skycity-events': ['-'],
        'category-label': ['-'],
        outright: ['no'],
        'ante-post': ['no'],
        country: ['ENG'],
        region: ['-'],
        category: ['-'],
    },
    inPlayDelaySettings: null,
    timeSettings: {
        startTime: '2025-01-30T10:00:00Z',
        started: false,
        tradedInPlay: true,
        offAtStartTime: false,
        timeZone: 'UTC',
    },
    feedData: {},
    participants: [
        {
            id: 1,
            role: 'home',
        },
        {
            id: 2,
            role: 'away',
        },
    ],
    statistics: {
        timer: {
            value: '',
        },
        period: {
            value: '',
        },
        substitution: {
            home: 0,
            away: 0,
        },
        'period-scores': [],
    },
    markets: [
        {
            id: 1,
            name: '1x2',
            active: true,
            autoTakeDown: null,
            display: true,
            displayOrder: 1,
            tradedInPlay: false,
            forecastsOffered: null,
            tricastsOffered: null,
            inPlayDelaySettings: null,
            sp: false,
            line: null,
            asianInPlayLine: null,
            cashoutAvailable: true,
            outright: false,
            bp: null,
            bpApplicable: null,
            spApplicable: null,
            spOnly: false,
            eachWayStakeReduction: null,
            betReferralEnabled: null,
            time: null,
            team: null,
            selections: [
                {
                    id: 1,
                    name: 'Liverpool',
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 2,
                        f: '1/1',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['H'],
                        'price-boost': ['no'],
                        'selection-identifier': ['H'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'bet-radar-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    metadata: {
                        silk: null,
                        silkUrl: null,
                        number: null,
                        weight: null,
                        drawn: null,
                        jockey: null,
                        trainer: null,
                        status: null,
                        place: null,
                    },
                },
                {
                    id: 2,
                    name: 'draw',
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 3,
                        f: '2/1',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['D'],
                        'price-boost': ['no'],
                        'selection-identifier': ['D'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'bet-radar-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                },
                {
                    id: 3,
                    name: 'Chelsea',
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 4,
                        f: '3/1',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['A'],
                        'price-boost': ['no'],
                        'selection-identifier': ['A'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'bet-radar-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    metadata: {
                        silk: null,
                        silkUrl: null,
                        number: null,
                        weight: null,
                        drawn: null,
                        jockey: null,
                        trainer: null,
                        status: null,
                        place: null,
                    },
                },
            ],
            suspendTime: null,
            event: {
                id: 1,
                name: 'Liverpool vs Chelsea',
            },
            speedBetContext: null,
            template: {
                id: 'bet-radar-1',
                eventTemplateId: 'match',
                customName: null,
                sportId: 'football',
                name: '1x2 (1)',
                marketTemplateType: '1',
                mainGroup: 'Match Result',
                period: 'Regular play',
                marketTypeGeneric: 'threewaywinner',
            },
            eachWay: null,
            tags: {
                'market-display': ['-'],
                'market-group--popular-markets': ['no'],
                'website-main': ['yes'],
                'asian-view': ['no'],
                'build-a-bet': ['no'],
                'market-group': ['Main'],
                'display-template': ['-'],
                outright: ['no'],
                'ante-post': ['no'],
                'display-order': ['-'],
                'website-popular': ['-'],
            },
            revision: 1,
            templateId: 'bet-radar-1',
        },
        {
            id: 2,
            name: 'Total',
            active: true,
            autoTakeDown: null,
            display: true,
            displayOrder: 3,
            tradedInPlay: false,
            forecastsOffered: null,
            tricastsOffered: null,
            inPlayDelaySettings: null,
            sp: false,
            line: 2,
            asianInPlayLine: null,
            cashoutAvailable: true,
            outright: false,
            bp: null,
            bpApplicable: null,
            spApplicable: null,
            spOnly: false,
            eachWayStakeReduction: null,
            betReferralEnabled: null,
            time: null,
            team: null,
            selections: [
                {
                    id: 4,
                    name: 'under 2.0',
                    nameWithoutLine: 'under',
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 1.5,
                        f: '1/2',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['U'],
                        'price-boost': ['no'],
                        'selection-identifier': ['U'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'bet-radar-18',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: '2.0',
                },
                {
                    id: 5,
                    name: 'over 2.0',
                    nameWithoutLine: 'over',
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 2.5,
                        f: '6/4',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['O'],
                        'price-boost': ['no'],
                        'selection-identifier': ['O'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'bet-radar-18',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: '2.0',
                },
            ],
            suspendTime: null,
            event: {
                id: 1,
                name: 'Liverpool vs Chelsea',
            },
            speedBetContext: null,
            template: {
                id: 'bet-radar-18',
                eventTemplateId: 'match',
                customName: null,
                sportId: 'football',
                name: 'Total (18)',
                marketTemplateType: '18',
                mainGroup: 'Totals',
                period: 'Regular play',
                marketTypeGeneric: 'overunder',
            },
            eachWay: null,
            tags: {
                'market-display': ['cross-bet-view'],
                'market-group--popular-markets': ['no'],
                'website-main': ['yes'],
                'asian-view': ['no'],
                'build-a-bet': ['no'],
                'market-group': ['Main', 'Asians', 'Goals'],
                'display-template': ['-'],
                outright: ['no'],
                'ante-post': ['no'],
                'display-order': ['-'],
                'website-popular': ['-'],
            },
            revision: 1,
            templateId: 'bet-radar-18',
        },
        {
            id: 6,
            name: 'Handicap',
            active: true,
            autoTakeDown: null,
            display: true,
            displayOrder: 2,
            tradedInPlay: false,
            forecastsOffered: null,
            tricastsOffered: null,
            inPlayDelaySettings: null,
            sp: false,
            line: 0.25,
            asianInPlayLine: null,
            cashoutAvailable: true,
            outright: false,
            bp: null,
            bpApplicable: null,
            spApplicable: null,
            spOnly: false,
            eachWayStakeReduction: null,
            betReferralEnabled: null,
            time: null,
            team: null,
            selections: [
                {
                    id: 12,
                    name: 'Liverpool (+0.25)',
                    nameWithoutLine: 'Liverpool',
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 3.3,
                        f: '23/10',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['H'],
                        'price-boost': ['no'],
                        'selection-identifier': ['H'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'bet-radar-16',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: '+0.25',
                },
                {
                    id: 13,
                    name: 'Chelsea (-0.25)',
                    nameWithoutLine: 'Chelsea',
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 4.5,
                        f: '7/2',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['A'],
                        'price-boost': ['no'],
                        'selection-identifier': ['A'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'bet-radar-16',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: '-0.25',
                },
            ],
            suspendTime: null,
            event: {
                id: 1,
                name: 'Liverpool vs Chelsea',
            },
            speedBetContext: null,
            template: {
                id: 'bet-radar-16',
                eventTemplateId: 'match',
                customName: null,
                sportId: 'football',
                name: 'Handicap (16)',
                marketTemplateType: '16',
                mainGroup: 'Spreads',
                period: 'Regular play',
                marketTypeGeneric: 'twowayhandicap',
            },
            eachWay: null,
            tags: {
                'market-display': ['cross-bet-view'],
                'market-group--popular-markets': ['no'],
                'website-main': ['yes'],
                'asian-view': ['no'],
                'build-a-bet': ['no'],
                'market-group': ['Main', 'Asians'],
                'display-template': ['-'],
                outright: ['no'],
                'ante-post': ['no'],
                'display-order': ['-'],
                'website-popular': ['-'],
            },
            revision: 1,
            templateId: 'bet-radar-16',
        },
        {
            id: 10,
            name: '1st half - 1x2',
            active: true,
            autoTakeDown: null,
            display: true,
            displayOrder: 13,
            tradedInPlay: false,
            forecastsOffered: null,
            tricastsOffered: null,
            inPlayDelaySettings: null,
            sp: false,
            line: null,
            asianInPlayLine: null,
            cashoutAvailable: true,
            outright: false,
            bp: null,
            bpApplicable: null,
            spApplicable: null,
            spOnly: false,
            eachWayStakeReduction: null,
            betReferralEnabled: null,
            time: null,
            team: null,
            selections: [
                {
                    id: 20,
                    name: 'Liverpool',
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 2,
                        f: '1/1',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['H'],
                        'price-boost': ['no'],
                        'selection-identifier': ['H'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'bet-radar-60',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    metadata: {
                        silk: null,
                        silkUrl: null,
                        number: null,
                        weight: null,
                        drawn: null,
                        jockey: null,
                        trainer: null,
                        status: null,
                        place: null,
                    },
                },
                {
                    id: 21,
                    name: 'draw',
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 3,
                        f: '2/1',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['D'],
                        'price-boost': ['no'],
                        'selection-identifier': ['D'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'bet-radar-60',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                },
                {
                    id: 22,
                    name: 'Chelsea',
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 4,
                        f: '3/1',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['A'],
                        'price-boost': ['no'],
                        'selection-identifier': ['A'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'bet-radar-60',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    metadata: {
                        silk: null,
                        silkUrl: null,
                        number: null,
                        weight: null,
                        drawn: null,
                        jockey: null,
                        trainer: null,
                        status: null,
                        place: null,
                    },
                },
            ],
            suspendTime: null,
            event: {
                id: 1,
                name: 'Liverpool vs Chelsea',
            },
            speedBetContext: null,
            template: {
                id: 'bet-radar-60',
                eventTemplateId: 'match',
                customName: null,
                sportId: 'football',
                name: '1st half - 1x2 (60)',
                marketTemplateType: '60',
                mainGroup: 'Match Result',
                period: '1st half',
                marketTypeGeneric: 'threewaywinner',
            },
            eachWay: null,
            tags: {
                'market-display': ['cross-bet-view'],
                'market-group--popular-markets': ['no'],
                'website-main': ['yes'],
                'asian-view': ['no'],
                'build-a-bet': ['no'],
                'market-group': ['Main', 'Halves'],
                'display-template': ['-'],
                outright: ['no'],
                'ante-post': ['no'],
                'display-order': ['-'],
                'website-popular': ['-'],
            },
            revision: 1,
            templateId: 'bet-radar-60',
        },
        {
            id: 11,
            name: '1st half - handicap',
            active: true,
            autoTakeDown: null,
            display: true,
            displayOrder: 15,
            tradedInPlay: false,
            forecastsOffered: null,
            tricastsOffered: null,
            inPlayDelaySettings: null,
            sp: false,
            line: 2,
            asianInPlayLine: null,
            cashoutAvailable: true,
            outright: false,
            bp: null,
            bpApplicable: null,
            spApplicable: null,
            spOnly: false,
            eachWayStakeReduction: null,
            betReferralEnabled: null,
            time: null,
            team: null,
            selections: [
                {
                    id: 23,
                    name: 'Liverpool (+2)',
                    nameWithoutLine: 'Liverpool',
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 3.5,
                        f: '5/2',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['H'],
                        'price-boost': ['no'],
                        'selection-identifier': ['H'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'bet-radar-66',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: '+2',
                },
                {
                    id: 24,
                    name: 'Chelsea (-2)',
                    nameWithoutLine: 'Chelsea',
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 4.5,
                        f: '7/2',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['A'],
                        'price-boost': ['no'],
                        'selection-identifier': ['A'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'bet-radar-66',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: '-2',
                },
            ],
            suspendTime: null,
            event: {
                id: 1,
                name: 'Liverpool vs Chelsea',
            },
            speedBetContext: null,
            template: {
                id: 'bet-radar-66',
                eventTemplateId: 'match',
                customName: null,
                sportId: 'football',
                name: '1st half - handicap (66)',
                marketTemplateType: '66',
                mainGroup: 'Spreads',
                period: '1st half',
                marketTypeGeneric: 'twowayhandicap',
            },
            eachWay: null,
            tags: {
                'market-display': ['cross-bet-view'],
                'market-group--popular-markets': ['no'],
                'website-main': ['yes'],
                'asian-view': ['no'],
                'build-a-bet': ['no'],
                'market-group': ['Main', 'Asians', 'Halves'],
                'display-template': ['-'],
                outright: ['no'],
                'ante-post': ['no'],
                'display-order': ['-'],
                'website-popular': ['-'],
            },
            revision: 1,
            templateId: 'bet-radar-60',
        },
        {
            id: 16,
            name: '1st half - total',
            active: true,
            autoTakeDown: null,
            display: true,
            displayOrder: 16,
            tradedInPlay: false,
            forecastsOffered: null,
            tricastsOffered: null,
            inPlayDelaySettings: null,
            sp: false,
            line: 2.25,
            asianInPlayLine: null,
            cashoutAvailable: true,
            outright: false,
            bp: null,
            bpApplicable: null,
            spApplicable: null,
            spOnly: false,
            eachWayStakeReduction: null,
            betReferralEnabled: null,
            time: null,
            team: null,
            selections: [33, 34],
            suspendTime: null,
            event: {
                id: 1,
                name: 'Liverpool vs Chelsea',
            },
            speedBetContext: null,
            template: {
                id: 'bet-radar-68',
                eventTemplateId: 'match',
                customName: null,
                sportId: 'football',
                name: '1st half - total (68)',
                marketTemplateType: '68',
                mainGroup: 'Totals',
                period: '1st half',
                marketTypeGeneric: 'overunder',
            },
            eachWay: null,
            tags: {
                'market-display': ['cross-bet-view'],
                'market-group--popular-markets': ['no'],
                'website-main': ['yes'],
                'asian-view': ['no'],
                'build-a-bet': ['no'],
                'market-group': ['Main', 'Asians', 'Goals', 'Halves'],
                'display-template': ['-'],
                outright: ['no'],
                'ante-post': ['no'],
                'display-order': ['-'],
                'website-popular': ['-'],
            },
            revision: 1,
            templateId: 'bet-radar-68',
        },
    ],
    marketIndex: [
        {
            id: 1,
            name: '1x2',
            templateId: 'bet-radar-1',
            active: true,
            display: true,
            marketType: 'threewaywinner',
            marketState: 'open',
            outright: false,
        },
        {
            id: 10,
            name: '1st half - 1x2',
            templateId: 'bet-radar-60',
            active: true,
            display: true,
            marketType: 'threewaywinner',
            marketState: 'open',
            outright: false,
        },
        {
            id: 11,
            name: '1st half - handicap',
            templateId: 'bet-radar-66',
            active: true,
            display: true,
            marketType: 'twowayhandicap',
            marketState: 'open',
            outright: false,
        },
        {
            id: 16,
            name: '1st half - total',
            templateId: 'bet-radar-68',
            active: true,
            display: true,
            marketType: 'overunder',
            marketState: 'open',
            outright: false,
        },
        {
            id: 2,
            name: 'Total',
            templateId: 'bet-radar-18',
            active: true,
            display: true,
            marketType: 'overunder',
            marketState: 'open',
            outright: false,
        },
        {
            id: 9,
            name: 'Handicap',
            templateId: 'bet-radar-16',
            active: true,
            display: true,
            marketType: 'twowayhandicap',
            marketState: 'open',
            outright: false,
        },
    ],
    translationData: {
        event: 'Liverpool vs Chelsea',
        competition: 'Premier League',
        participants: ['Liverpool', 'Chelsea'],
    },
    media: {
        statistics: [],
        liveTrackers: [],
        streams: [],
    },
    revision: 10,
};
