import type { CountriesById } from './types';

export const countriesById: CountriesById = Object.freeze({
    '-': 'All',
    AFG: 'Afghanistan',
    AFR: 'Africa',
    ALB: 'Albania',
    ALG: 'Algeria',
    AME: 'America',
    ASA: 'American Samoa',
    AND: 'Andorra',
    ANG: 'Angola',
    AIA: 'Anguilla',
    ANT: 'Antigua and Barbuda',
    ARG: 'Argentina',
    ARM: 'Armenia',
    ARU: 'Aruba',
    ASI: 'Asia',
    AUS: 'Australia',
    AUT: 'Austria',
    AZE: 'Azerbaijan',
    BAH: 'Bahamas',
    BRN: 'Bahrain',
    BAN: 'Bangladesh',
    BAR: 'Barbados',
    BLR: 'Belarus',
    BEL: 'Belgium',
    BIZ: 'Belize',
    BEN: 'Benin',
    BER: 'Bermuda',
    BHU: 'Bhutan',
    BOL: 'Bolivia',
    BIH: 'Bosnia and Herzegovina',
    BOT: 'Botswana',
    BRA: 'Brasil',
    BRU: 'Brunei Darussalam',
    BUL: 'Bulgaria',
    BUR: 'Burkina Faso',
    BDI: 'Burundi',
    CAM: 'Cambodia',
    CMR: 'Cameroon',
    CAN: 'Canada',
    CPV: 'Cape Verde',
    CAY: 'Cayman Islands',
    CAF: 'Central African Republic',
    CHA: 'Chad',
    CHI: 'Chile',
    CHN: 'China',
    COL: 'Colombia',
    COM: 'Comoros',
    CGO: 'Congo',
    COD: 'Congo, Democratic Republic',
    COK: 'Cook Islands',
    CRC: 'Costa Rica',
    CIV: 'Côte d Ivoire',
    CRO: 'Croatia',
    CUB: 'Cuba',
    CYP: 'Cyprus',
    CZE: 'Czech Republic',
    DEN: 'Denmark',
    DJI: 'Djibouti',
    DMA: 'Dominica',
    DOM: 'Dominican Republic',
    AHO: 'Dutch Antilles',
    ECU: 'Ecuador',
    EGY: 'Egypt',
    ESA: 'El Salvador',
    ENG: 'England',
    EQU: 'Equator',
    GEQ: 'Equatorial Guinea',
    ERI: 'Eritrea',
    EST: 'Estonia',
    ETH: 'Ethiopia',
    EUR: 'Europe',
    FRO: 'Faroe Islands',
    FIJ: 'Fiji Islands',
    FIN: 'Finland',
    FRA: 'France',
    GUF: 'French Guinea',
    GAB: 'Gabon',
    GAM: 'Gambia',
    GEO: 'Georgien',
    GER: 'Germany',
    GHA: 'Ghana',
    GIB: 'Gibraltar',
    GRE: 'Greece',
    GRL: 'Greenland',
    GRN: 'Grenada',
    GUM: 'Guam',
    GUA: 'Guatemala',
    GUI: 'Guinea',
    GBS: 'Guinea-Bissau',
    GUY: 'Guyana',
    HAI: 'Haiti',
    HON: 'Honduras',
    HKG: 'Hongkong',
    HUN: 'Hungary',
    ISL: 'Iceland',
    IND: 'India',
    INA: 'Indonesia',
    IRI: 'Iran',
    IRQ: 'Iraq',
    ISR: 'Israel',
    ITA: 'Italy',
    JAM: 'Jamaica',
    JPN: 'Japan',
    JOR: 'Jordan',
    KAZ: 'Kazakhstan',
    KEN: 'Kenya',
    PRK: 'Korea (North)',
    KOR: 'Korea (South)',
    XK: 'Kosovo',
    KUW: 'Kuwait',
    KGZ: 'Kyrgyzstan',
    LAO: 'Laos',
    LAT: 'Latvia',
    LIB: 'Lebanon',
    LES: 'Lesotho',
    LBR: 'Liberia',
    LBY: 'Libya',
    LIE: 'Liechtenstein',
    LTU: 'Lithuania',
    NOE: 'Lower Austria',
    LUX: 'Luxembourg',
    MAC: 'Macau',
    MKD: 'Macedonia',
    MAD: 'Madagascar',
    MAW: 'Malawi',
    MAS: 'Malaysia',
    MDV: 'Maldives',
    MLI: 'Mali',
    MLT: 'Malta',
    MTN: 'Mauritania',
    MRI: 'Mauritius',
    MEX: 'Mexico',
    FSM: 'Micronesia',
    MDA: 'Moldova',
    MON: 'Monaco',
    MGL: 'Mongolia',
    MTG: 'Montenegro',
    MSR: 'Montserrat',
    MAR: 'Morocco',
    MOZ: 'Mozambique',
    MYA: 'Myanmar1',
    NAM: 'Namibia',
    NRU: 'Nauru',
    NEP: 'Nepal',
    NED: 'Netherland',
    NZL: 'New Zealand',
    NCA: 'Nicaragua',
    NIG: 'Niger',
    NGR: 'Nigeria',
    'N-A': 'North America',
    NIR: 'Northern Ireland',
    NOR: 'Norway',
    OCE: 'Oceania',
    OLY: 'Olympics',
    OMA: 'Oman',
    PAK: 'Pakistan',
    PLW: 'Palau Islands',
    PAL: 'Palestine',
    PAN: 'Panama',
    PNG: 'Papua New Guinea',
    PAR: 'Paraguay',
    PER: 'Peru',
    PHI: 'Philippines',
    POL: 'Poland',
    POR: 'Portugal',
    PUR: 'Puerto Rico',
    QAT: 'Qatar',
    IRL: 'Republic of Ireland',
    ROM: 'Romania',
    RUS: 'Russia',
    RWA: 'Rwanda',
    SAM: 'Samoa (Selbständig)',
    SMR: 'San Marino',
    STP: 'São Tomé und Principe',
    KSA: 'Saudi Arabia',
    SCA: 'Scandinavia',
    SCO: 'Scotland',
    SEN: 'Senegal',
    SRB: 'Serbia',
    YUG: 'Serbia and Montenegro',
    SEY: 'Seychelles',
    SLE: 'Sierra Leone',
    SIN: 'Singapore',
    SVK: 'Slovakia',
    SLO: 'Slovenia',
    SOL: 'Solomon Islands',
    SOM: 'Somalia',
    RSA: 'South Africa',
    'S-A': 'South America',
    ESP: 'Spain',
    SRI: 'Sri Lanka',
    VIN: 'St Vincent and Grenadines',
    SKN: 'St. Kitts und Nevis',
    LCA: 'St.Lucia',
    SUD: 'Sudan',
    SUR: 'Surinam',
    SWZ: 'Swaziland',
    SWE: 'Sweden',
    SUI: 'Switzerland',
    SYR: 'Syria',
    TAH: 'Tahiti',
    TPE: 'Taiwan',
    TJK: 'Tajikistan',
    TAN: 'Tanzania',
    THA: 'Thailand',
    TOG: 'Togo',
    TGA: 'Tonga',
    TRI: 'Trinidad and Tobago',
    TUN: 'Tunisia',
    TUR: 'Turkey',
    TKM: 'Turkmenistan',
    TCA: 'Turks and Caicos Islands',
    UGA: 'Uganda',
    UKR: 'Ukraine',
    UAE: 'United Arab Emirates',
    GBR: 'United Kingdom',
    ISV: 'United States Virgin Islands',
    URU: 'Uruguay',
    USA: 'USA',
    UZB: 'Uzbekistan',
    VAN: 'Vanuatu',
    VEN: 'Venezuela',
    VIE: 'Vietnam',
    IVB: 'Virgin Islands (British)',
    WAL: 'Wales',
    WRL: 'World',
    YEM: 'Yemen',
    ZAM: 'Zambia',
    ZIM: 'Zimbabwe',
} as const);
