import type { SportIcons } from './types';

export const SPORT_ICONS: SportIcons = {
    all: 'sports-all',
    live: 'sports-live',
    badgelive: 'sports-badge-live',
    video: 'sports-glyph-video-i',
    default: 'sports-globe',
    americanfootball: 'sports-11',
    australianrules: 'sports-36',
    baseball: 'sports-23',
    basketball: 'sports-7',
    boxing: 'sports-24',
    combatsports: 'sports-45',
    cricket: 'sports-22',
    cycling: 'sports-10',
    darts: 'sports-34',
    football: 'sports-4',
    golf: 'sports-13',
    handball: 'sports-16',
    horseracing: 'sports-46',
    icehockey: 'sports-12',
    motorsport: 'sports-41',
    politics: 'theme-politics',
    rugbyleague: 'sports-31',
    rugbyunion: 'sports-32',
    snooker: 'sports-33',
    tabletennis: 'sports-56',
    tennis: 'sports-5',
    biathlon: 'sports-64',
    crosscountryskiing: 'sports-94',
    volleyball: 'sports-18',
    motorbikes: 'sports-40',
    nordiccombined: 'sports-96',
    skijumping: 'sports-95',
    badminton: 'theme-badminton',
    beachvolleyball: 'theme-beach_handball',
    formulaone: 'theme-formula1',
    futsal: 'theme-futsal',
    skialpine: 'theme-skiing',
    speedskating: 'theme-speedscating',
    specials: 'theme-specials',
    tvandspecials: 'theme-TVSPECIALS',
    olympicgames: 'OLYMPICGAMES', // css class-name
    starcraft: 'sports-starcraft',
    dota2: 'sports-dota2',
    lol: 'sports-lol',
    csgo: 'sports-csgo',
};
