import { getFromSsr } from 'src/appState/app-state-helper';

test('should return null if value is not generated by SSR', () => {
    expect(getFromSsr({}, '$foo', 'bar')).toBeNull();
    expect(getFromSsr({ $foo: `${JSON.stringify('')}` }, '$foo', 'bar')).toBeNull();
    expect(getFromSsr({ $foo: `${JSON.stringify({})}` }, '$foo', 'bar')).toBeNull();
});

test('should return the value if it was "generated" by SSR', () => {
    expect(getFromSsr<string>({ $foo: `${JSON.stringify({ bar: 'baz' })}` }, '$foo', 'bar')).toBe('baz');
    expect(getFromSsr<string>({ $foo: `${JSON.stringify({ bar: 'baz' })}` }, '$foo')).toEqual({ bar: 'baz' });
});
