export enum Channel {
    Desktop = 'desktop',
    Mobile = 'mobile',
    QuickBet = 'quickbet',
}

export enum PossibleBetsTriggeredBy {
    BetslipInit = 'BETSLIP_INIT',
    AcceptBetChanges = 'ACCEPT_BET_CHANGES',
    AddSelection = 'ADD_SELECTION',
    AddBuildABetSelection = 'ADD_BAB_SELECTION',
    BetPriceChanged = 'BET_PRICE_CHANGED',
    ChangeBetslipTab = 'CHANGE_BETSLIP_TAB',
    ChangeSystemBetType = 'CHANGE_SYSTEM_BET_TYPE',
    ClearOffer = 'CLEAR_OFFER',
    SetOffer = 'SET_OFFER',
    KeepPlacedBets = 'KEEP_PLACED_BETS',
    RefreshEventTimeOut = 'REFRESH_EVENT_TIMEOUT',
    RemoveBet = 'REMOVE_BET',
    RemoveSelection = 'REMOVE_SELECTION',
    RemoveBuildABetSelection = 'REMOVE_BAB_SELECTION',
    RemoveOrphanSelections = 'REMOVE_ORPHAN_SELECTIONS',
    ReplaceOrphanSelections = 'REPLACE_ORPHAN_SELECTIONS',
    SelectFreeBet = 'SELECT_FREE_BET',
    ToggleFreeBet = 'TOGGLE_FREE_BET',
    SubstituteFromSameMarketType = 'SUBSTITUTE_FROM_SAME_MARKET_TYPE',
    SubstituteFromDifferentMarketType = 'SUBSTITUTE_FROM_DIFFERENT_MARKET_TYPE',
    SyncBetslipPrices = 'SYNC_BETSLIP_PRICES',
    SyncBuildABetStake = 'SYNC_BAB_STAKE',
    ToggleBetslipBet = 'TOGGLE_BETSLIP_BET',
    ToggleAllBetslipBets = 'TOGGLE_ALL_BETSLIP_BETS',
    UpdateCombinationStake = 'UPDATE_COMBINATION_STAKE',
    UpdateSingleBetStake = 'UPDATE_SINGLE_BET_STAKE',
    UpdateSingleBetStakes = 'UPDATE_SINGLE_BET_STAKES',
    WalletUpdate = 'WALLET_UPDATE',
}
