import type { AsianViewSportConfig } from '@solo-asianView/api/cms/types';
import type { EventGroup } from '@solo-asianView/types';

import type { MarketItem } from 'src/store/events/types';

export const winnerMarket: MarketItem = {
    id: 12394,
    name: '1x2',
    active: true,
    autoTakeDown: null,
    display: true,
    displayOrder: 1,
    tradedInPlay: false,
    forecastsOffered: null,
    tricastsOffered: null,
    inPlayDelaySettings: null,
    sp: false,
    line: null,
    cashoutAvailable: true,
    outright: false,
    bp: null,
    bpApplicable: null,
    spApplicable: null,
    spOnly: false,
    eachWayStakeReduction: null,
    betReferralEnabled: null,
    time: null,
    team: null,
    selections: [
        {
            id: 39374,
            name: 'Juve Stabia',
            active: true,
            display: true,
            displayOrder: 0,
            price: {
                d: 1.71,
                f: '71/100',
            },
            state: 'open',
            tags: {
                'selection-identifiers--football': ['H'],
                'price-boost': ['no'],
                'selection-identifier': ['H'],
            },
            template: {
                id: 'default-selection',
                marketTemplateId: 'bet-radar-1',
                eventTemplateId: 'match',
                sportId: 'football',
                name: 'default-selection',
            },
            metadata: {
                silk: null,
                silkUrl: null,
                number: null,
                weight: null,
                drawn: null,
                jockey: null,
                trainer: null,
                status: null,
                place: null,
            },
        },
        {
            id: 39376,
            name: 'Casertana FC',
            active: true,
            display: true,
            displayOrder: 0,
            price: {
                d: 4.8,
                f: '19/5',
            },
            state: 'open',
            tags: {
                'selection-identifiers--football': ['A'],
                'price-boost': ['no'],
                'selection-identifier': ['A'],
            },
            template: {
                id: 'default-selection',
                marketTemplateId: 'bet-radar-1',
                eventTemplateId: 'match',
                sportId: 'football',
                name: 'default-selection',
            },
            metadata: {
                silk: null,
                silkUrl: null,
                number: null,
                weight: null,
                drawn: null,
                jockey: null,
                trainer: null,
                status: null,
                place: null,
            },
        },
        {
            id: 39375,
            name: 'draw',
            active: true,
            display: true,
            displayOrder: 0,
            price: {
                d: 3.5,
                f: '5/2',
            },
            state: 'open',
            tags: {
                'selection-identifiers--football': ['D'],
                'price-boost': ['no'],
                'selection-identifier': ['D'],
            },
            template: {
                id: 'default-selection',
                marketTemplateId: 'bet-radar-1',
                eventTemplateId: 'match',
                sportId: 'football',
                name: 'default-selection',
            },
        },
    ],
    suspendTime: null,
    event: {
        id: 423,
        name: 'Juve Stabia vs Casertana FC',
    },
    template: {
        id: 'bet-radar-1',
        eventTemplateId: 'match',
        customName: null,
        sportId: 'football',
        name: '1x2 (1)',
        marketTemplateType: '1',
        mainGroup: 'Match Result',
        period: 'Regular play',
        marketTypeGeneric: 'threewaywinner',
    },
    eachWay: null,
    tags: {
        'market-display': ['-'],
        'market-group--popular-markets': ['no'],
        'website-main': ['yes'],
        'asian-view': ['yes'],
        'build-a-bet': ['no'],
        'market-group': ['Main'],
        'display-template': ['-'],
        outright: ['no'],
        'ante-post': ['no'],
        'display-order': ['-'],
        'website-popular': ['-'],
    },
    revision: 0,
} as unknown as MarketItem;

export const totalMarket: MarketItem = {
    id: 12359,
    name: 'Total',
    active: true,
    autoTakeDown: null,
    display: true,
    displayOrder: 3,
    tradedInPlay: false,
    forecastsOffered: null,
    tricastsOffered: null,
    inPlayDelaySettings: null,
    sp: false,
    line: 2.25,
    cashoutAvailable: true,
    outright: false,
    bp: null,
    bpApplicable: null,
    spApplicable: null,
    spOnly: false,
    eachWayStakeReduction: null,
    betReferralEnabled: null,
    time: null,
    team: null,
    selections: [
        {
            id: 39295,
            name: 'over 2.25',
            nameWithoutLine: 'over',
            active: true,
            display: true,
            displayOrder: 0,
            price: {
                d: 1.96,
                f: '24/25',
            },
            state: 'open',
            tags: {
                'selection-identifiers--football': ['O'],
                'price-boost': ['no'],
                'selection-identifier': ['O'],
            },
            template: {
                id: 'default-selection',
                marketTemplateId: 'bet-radar-18',
                eventTemplateId: 'match',
                sportId: 'football',
                name: 'default-selection',
            },
            line: '2.25',
        },
        {
            id: 39296,
            name: 'under 2.25',
            nameWithoutLine: 'under',
            active: true,
            display: true,
            displayOrder: 0,
            price: {
                d: 1.82,
                f: '41/50',
            },
            state: 'open',
            tags: {
                'selection-identifiers--football': ['U'],
                'price-boost': ['no'],
                'selection-identifier': ['U'],
            },
            template: {
                id: 'default-selection',
                marketTemplateId: 'bet-radar-18',
                eventTemplateId: 'match',
                sportId: 'football',
                name: 'default-selection',
            },
            line: '2.25',
        },
    ],
    suspendTime: null,
    event: {
        id: 423,
        name: 'Juve Stabia vs Casertana FC',
    },
    template: {
        id: 'bet-radar-18',
        eventTemplateId: 'match',
        customName: null,
        sportId: 'football',
        name: 'Total (18)',
        marketTemplateType: '18',
        mainGroup: 'Totals',
        period: 'Regular play',
        marketTypeGeneric: 'overunder',
    },
    eachWay: null,
    tags: {
        'market-display': ['-'],
        'market-group--popular-markets': ['no'],
        'website-main': ['yes'],
        'asian-view': ['yes'],
        'build-a-bet': ['no'],
        'market-group': ['Main', 'Asians', 'Goals'],
        'display-template': ['-'],
        outright: ['no'],
        'ante-post': ['no'],
        'display-order': ['-'],
        'website-popular': ['-'],
    },
    revision: 0,
} as unknown as MarketItem;

export const handicapMarket: MarketItem = {
    id: 12411,
    name: 'Handicap',
    active: true,
    autoTakeDown: null,
    display: true,
    displayOrder: 2,
    tradedInPlay: false,
    forecastsOffered: null,
    tricastsOffered: null,
    inPlayDelaySettings: null,
    sp: false,
    line: -0.75,
    cashoutAvailable: true,
    outright: false,
    bp: null,
    bpApplicable: null,
    spApplicable: null,
    spOnly: false,
    eachWayStakeReduction: null,
    betReferralEnabled: null,
    time: null,
    team: null,
    selections: [
        {
            id: 39425,
            name: 'Juve Stabia (-0.75)',
            nameWithoutLine: 'Juve Stabia',
            active: true,
            display: true,
            displayOrder: 0,
            price: {
                d: 1.94,
                f: '47/50',
            },
            state: 'open',
            tags: {
                'selection-identifiers--football': ['H'],
                'price-boost': ['no'],
                'selection-identifier': ['H'],
            },
            template: {
                id: 'default-selection',
                marketTemplateId: 'bet-radar-16',
                eventTemplateId: 'match',
                sportId: 'football',
                name: 'default-selection',
            },
            line: '-0.75',
        },
        {
            id: 39426,
            name: 'Casertana FC (+0.75)',
            nameWithoutLine: 'Casertana FC',
            active: true,
            display: true,
            displayOrder: 0,
            price: {
                d: 1.84,
                f: '21/25',
            },
            state: 'open',
            tags: {
                'selection-identifiers--football': ['A'],
                'price-boost': ['no'],
                'selection-identifier': ['A'],
            },
            template: {
                id: 'default-selection',
                marketTemplateId: 'bet-radar-16',
                eventTemplateId: 'match',
                sportId: 'football',
                name: 'default-selection',
            },
            line: '+0.75',
        },
    ],
    suspendTime: null,
    event: {
        id: 423,
        name: 'Juve Stabia vs Casertana FC',
    },
    template: {
        id: 'bet-radar-16',
        eventTemplateId: 'match',
        customName: null,
        sportId: 'football',
        name: 'Handicap (16)',
        marketTemplateType: '16',
        mainGroup: 'Spreads',
        period: 'Regular play',
        marketTypeGeneric: 'twowayhandicap',
    },
    eachWay: null,
    tags: {
        'market-display': ['-'],
        'market-group--popular-markets': ['no'],
        'website-main': ['yes'],
        'asian-view': ['yes'],
        'build-a-bet': ['no'],
        'market-group': ['Main', 'Asians'],
        'display-template': ['-'],
        outright: ['no'],
        'ante-post': ['no'],
        'display-order': ['-'],
        'website-popular': ['-'],
    },
    revision: 0,
} as unknown as MarketItem;

export const mockedSportConfig: AsianViewSportConfig = {
    id: 1,
    sport: 'football',
    startTime: 'Time',
    event: 'Match',
    primaryGroup: {
        name: 'Full Time',
        markets: [
            {
                id: 'bet-radar-1',
                name: '1x2',
                order: 1,
            },
            {
                id: 'bet-radar-18',
                name: 'O/U',
                order: 2,
            },
            {
                id: 'bet-radar-16',
                name: 'HDP',
                order: 3,
            },
        ],
    },
    secondaryGroup: {
        name: '1st Half',
        markets: [
            {
                id: 'bet-radar-60',
                name: '1x2',
                order: 1,
            },
            {
                id: 'bet-radar-68',
                name: 'O/U',
                order: 2,
            },
            {
                id: 'bet-radar-66',
                name: 'HDP',
                order: 3,
            },
        ],
    },
};

export const mockedEventGroupForHeader: EventGroup = {
    tag: 'country',
    category: 'AUS',
    categoryLabel: 'Australia',
    id: 89,
    name: 'South Australia NPL',
    platformObject: {
        id: '02_sr:tournament:1258',
        name: 'South Australia NPL',
        externalId: {
            instance: 'solo',
            provider: 'bet-radar',
            feedId: 'sr:tournament:1258',
            sportId: 'bet-radar',
        },
    },
    events: [],
};
