import type { AggregatedSport } from '@solo-asianView/types';

import type { SportType } from 'src/common/enums';

export const sportsMock: Record<SportType, AggregatedSport> = {
    football: {
        id: 'football',
        name: 'Football',
        tags: {
            'website-show': ['yes'],
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', 'Asians', 'Goals', 'Halves', 'Team', 'Corners', 'Cards', 'Players'],
            region: ['-'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 100,
        eventCount: 1159,
        translations: {},
    },
    icehockey: {
        id: 'icehockey',
        name: 'Ice Hockey',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', 'Periods', 'Game Props', 'Player Props'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 94,
        eventCount: 181,
        translations: {},
    },
    basketball: {
        id: 'basketball',
        name: 'Basketball',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', 'Halves', 'Quarters', 'Game Props', 'Player Props'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 99,
        eventCount: 161,
        translations: {},
    },
    tabletennis: {
        id: 'tabletennis',
        name: 'Table Tennis',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 91,
        eventCount: 116,
        translations: {},
    },
    americanfootball: {
        id: 'americanfootball',
        name: 'American Football',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', 'Halves', 'Quarters', 'Game Props', 'Player Props'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 97,
        eventCount: 94,
        translations: {},
    },
    handball: {
        id: 'handball',
        name: 'Handball',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', 'Halves'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 81,
        eventCount: 90,
        translations: {},
    },
    boxing: {
        id: 'boxing',
        name: 'Boxing/MMA',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', 'Other'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 89,
        eventCount: 56,
        translations: {},
    },
    tennis: {
        id: 'tennis',
        name: 'Tennis',
        tags: {
            'solo-events': ['-'],
            'market-group': ['Main', 'Game Bets', 'Set Bets'],
            'tennis-tour': ['-'],
            highlight: ['no'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 96,
        eventCount: 55,
        translations: {},
    },
    volleyball: {
        id: 'volleyball',
        name: 'Volleyball',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 95,
        eventCount: 51,
        translations: {},
    },
    specials: {
        id: 'specials',
        name: 'Specials',
        tags: {
            'market-group': [],
        },
        displayOrder: 72,
        eventCount: 47,
        translations: {},
    },
    rugbyunion: {
        id: 'rugbyunion',
        name: 'Rugby Union',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', 'Halftime', 'Players'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 82,
        eventCount: 35,
        translations: {},
    },
    darts: {
        id: 'darts',
        name: 'Darts',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', 'Handicaps', "180's", 'Totals', 'Set Betting'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 88,
        eventCount: 27,
        translations: {},
    },
    golf: {
        id: 'golf',
        name: 'Golf',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', 'Special Bets', 'Outrights', 'Specials Bets'],
            'golf-tour': ['-'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 87,
        eventCount: 13,
        translations: {},
    },
    baseball: {
        id: 'baseball',
        name: 'Baseball',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', '1st 5 Innings', 'Innings', 'Game Props', 'Player Props'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 98,
        eventCount: 12,
        translations: {},
    },
    lol: {
        id: 'lol',
        name: 'League of Legends',
        tags: {
            'solo-events': ['-'],
            'market-group': ['-'],
            category: ['-'],
            'asian-view': ['no'],
            highlight: ['no'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 74,
        eventCount: 9,
        translations: {},
    },
    futsal: {
        id: 'futsal',
        name: 'Futsal',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', 'Handicap', 'Handicaps', 'Totals', 'Halves', 'Team', 'Race to', 'Other'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 85,
        eventCount: 6,
        translations: {},
    },
    formulaone: {
        id: 'formulaone',
        name: 'Formula One',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', 'Top Drivers', 'Head-to-head', 'Other/Specials', 'Outright'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 86,
        eventCount: 4,
        translations: {},
    },
    snooker: {
        id: 'snooker',
        name: 'Snooker',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', 'Frames', 'Breaks', 'Race to', 'Other'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 90,
        eventCount: 4,
        translations: {},
    },
    motorbikes: {
        id: 'motorbikes',
        name: 'Motorbikes',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', 'Outright'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 84,
        eventCount: 3,
        translations: {},
    },
    csgo: {
        id: 'csgo',
        name: 'CS:GO',
        tags: {
            esports: ['yes'],
            'market-group': ['-'],
            'asian-view': ['no'],
            outright: ['no'],
            'ante-post': ['no'],
            highlight: ['no'],
            country: ['-'],
            'solo-events': ['-'],
            category: ['-'],
        },
        displayOrder: 77,
        eventCount: 2,
        translations: {},
    },
    rugbyleague: {
        id: 'rugbyleague',
        name: 'Rugby League',
        tags: {
            highlight: ['no'],
            'solo-events': ['-'],
            'market-group': ['Main', 'Halftime', 'Players'],
            outright: ['no'],
            'ante-post': ['no'],
            country: ['-'],
        },
        displayOrder: 83,
        eventCount: 2,
        translations: {},
    },
    dota2: {
        id: 'dota2',
        name: 'Dota 2',
        tags: {
            esports: ['yes'],
            'market-group': ['-'],
            'asian-view': ['no'],
            outright: ['no'],
            'ante-post': ['no'],
            highlight: ['no'],
            country: ['-'],
            'solo-events': ['-'],
            category: ['-'],
        },
        displayOrder: 76,
        eventCount: 1,
        translations: {},
    },
} as unknown as Record<SportType, AggregatedSport>;
