import type { SpeedBetMarkets } from 'src/features/scoreboardWidget/types';

export const mockedSpeedBetMarketsAtom: SpeedBetMarkets = {
    ids: new Set([12805298, 12805297, 12804697, 12804834, 12805086, 12805197, 12805341]),
    markets: [
        {
            id: 12805341,
            name: 'NO SHOTS BY EITHER TEAM SO FAR. WHICH TEAM WILL TAKE THE FIRST SHOT AFTER 13:00? ⚽️ (EXCLUDING BLOCKED SHOTS)',
            active: false,
            autoTakeDown: null,
            display: true,
            displayOrder: 466,
            tradedInPlay: true,
            forecastsOffered: null,
            tricastsOffered: null,
            inPlayDelaySettings: null,
            sp: false,
            line: null,
            asianInPlayLine: null,
            cashoutAvailable: true,
            outright: false,
            bp: false,
            bpApplicable: false,
            spApplicable: false,
            spOnly: false,
            eachWayStakeReduction: null,
            betReferralEnabled: null,
            time: null,
            team: null,
            selections: {
                '34746560': {
                    id: 34746560,
                    name: 'NUJ',
                    nameWithoutLine: null,
                    active: false,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 1.96,
                        f: '24/25',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['N'],
                        'price-boost': ['no'],
                        'selection-identifier': ['N'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'kerosports-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: null,
                    asianInPlayLine: null,
                    nameWithPlaceholders: null,
                },
                '34746561': {
                    id: 34746561,
                    name: 'CCM',
                    nameWithoutLine: null,
                    active: false,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 1.75,
                        f: '3/4',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['Y'],
                        'price-boost': ['no'],
                        'selection-identifier': ['Y'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'kerosports-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: null,
                    asianInPlayLine: null,
                    nameWithPlaceholders: null,
                },
            },
            suspendTime: null,
            event: {
                id: 27072,
                name: 'Newcastle Jets vs Central Coast Mariners',
            },
            speedBetContext: {
                constraint: 'EXCLUDING BLOCKED SHOTS',
                contextNote: '0 shots for NUJ + CCM',
                isCore: false,
                timestamp: 1732267638038,
                translations: {},
            },
            template: {
                id: 'kerosports-1',
                eventTemplateId: 'match',
                customName: 'Fast Markets',
                sportId: 'football',
                name: 'Fast Markets (1)',
                marketTemplateType: 'kerosports-1',
                mainGroup: null,
                period: null,
                marketTypeGeneric: 'yesno',
            },
            eachWay: null,
            tags: {
                'market-display': ['-'],
                'market-group--popular-markets': ['no'],
                'website-main': ['no'],
                'asian-view': ['no'],
                'build-a-bet': ['no'],
                'market-group': ['Fast Markets'],
                'display-template': ['-'],
                outright: ['no'],
                'ante-post': ['no'],
                'display-order': ['-'],
                'website-popular': ['-'],
            },
            revision: 0,
        },
        {
            id: 12805197,
            name: 'CCM JUST TOOK THEIR FIRST SHOT IN 10 MINUTES! HOW MANY SHOTS WILL THEY TAKE BETWEEN 13:00 AND 22:59? ⚽️ (EXCLUDING BLOCKED SHOTS)',
            active: true,
            autoTakeDown: null,
            display: true,
            displayOrder: 466,
            tradedInPlay: true,
            forecastsOffered: null,
            tricastsOffered: null,
            inPlayDelaySettings: null,
            sp: false,
            line: null,
            asianInPlayLine: null,
            cashoutAvailable: true,
            outright: false,
            bp: false,
            bpApplicable: false,
            spApplicable: false,
            spOnly: false,
            eachWayStakeReduction: null,
            betReferralEnabled: null,
            time: null,
            team: null,
            selections: {
                '34746157': {
                    id: 34746157,
                    name: '0-1',
                    nameWithoutLine: null,
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 1.33,
                        f: '33/100',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['N'],
                        'price-boost': ['no'],
                        'selection-identifier': ['N'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'kerosports-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: null,
                    asianInPlayLine: null,
                    nameWithPlaceholders: null,
                },
                '34746158': {
                    id: 34746158,
                    name: '2+',
                    nameWithoutLine: null,
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 3.05,
                        f: '41/20',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['Y'],
                        'price-boost': ['no'],
                        'selection-identifier': ['Y'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'kerosports-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: null,
                    asianInPlayLine: null,
                    nameWithPlaceholders: null,
                },
            },
            suspendTime: null,
            event: {
                id: 27072,
                name: 'Newcastle Jets vs Central Coast Mariners',
            },
            speedBetContext: {
                constraint: 'EXCLUDING BLOCKED SHOTS',
                contextNote: '0.9 CCM shots per 10 min',
                isCore: false,
                timestamp: 1732267614876,
                translations: {},
            },
            template: {
                id: 'kerosports-1',
                eventTemplateId: 'match',
                customName: 'Fast Markets',
                sportId: 'football',
                name: 'Fast Markets (1)',
                marketTemplateType: 'kerosports-1',
                mainGroup: null,
                period: null,
                marketTypeGeneric: 'yesno',
            },
            eachWay: null,
            tags: {
                'market-display': ['-'],
                'market-group--popular-markets': ['no'],
                'website-main': ['no'],
                'asian-view': ['no'],
                'build-a-bet': ['no'],
                'market-group': ['Fast Markets'],
                'display-template': ['-'],
                outright: ['no'],
                'ante-post': ['no'],
                'display-order': ['-'],
                'website-popular': ['-'],
            },
            revision: 0,
        },
        {
            id: 12805086,
            name: '8 THROW-INS IN THE LAST 9 MIN! WILL THERE BE ANY BETWEEN 13:00 AND 14:59? ⤵️',
            active: false,
            autoTakeDown: null,
            display: true,
            displayOrder: 466,
            tradedInPlay: true,
            forecastsOffered: null,
            tricastsOffered: null,
            inPlayDelaySettings: null,
            sp: false,
            line: null,
            asianInPlayLine: null,
            cashoutAvailable: true,
            outright: false,
            bp: false,
            bpApplicable: false,
            spApplicable: false,
            spOnly: false,
            eachWayStakeReduction: null,
            betReferralEnabled: null,
            time: null,
            team: null,
            selections: {
                '34745909': {
                    id: 34745909,
                    name: 'NO',
                    nameWithoutLine: null,
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 2.34,
                        f: '67/50',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['N'],
                        'price-boost': ['no'],
                        'selection-identifier': ['N'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'kerosports-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: null,
                    asianInPlayLine: null,
                    nameWithPlaceholders: null,
                },
                '34745910': {
                    id: 34745910,
                    name: 'YES',
                    nameWithoutLine: null,
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 1.54,
                        f: '27/50',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['Y'],
                        'price-boost': ['no'],
                        'selection-identifier': ['Y'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'kerosports-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: null,
                    asianInPlayLine: null,
                    nameWithPlaceholders: null,
                },
            },
            suspendTime: null,
            event: {
                id: 27072,
                name: 'Newcastle Jets vs Central Coast Mariners',
            },
            speedBetContext: {
                constraint: null,
                contextNote: '2 throw ins per 2 min',
                isCore: false,
                timestamp: 1732267564932,
                translations: {},
            },
            template: {
                id: 'kerosports-1',
                eventTemplateId: 'match',
                customName: 'Fast Markets',
                sportId: 'football',
                name: 'Fast Markets (1)',
                marketTemplateType: 'kerosports-1',
                mainGroup: null,
                period: null,
                marketTypeGeneric: 'yesno',
            },
            eachWay: null,
            tags: {
                'market-display': ['-'],
                'market-group--popular-markets': ['no'],
                'website-main': ['no'],
                'asian-view': ['no'],
                'build-a-bet': ['no'],
                'market-group': ['Fast Markets'],
                'display-template': ['-'],
                outright: ['no'],
                'ante-post': ['no'],
                'display-order': ['-'],
                'website-popular': ['-'],
            },
            revision: 0,
        },
        {
            id: 12804834,
            name: 'WHICH TEAM TAKES THE NEXT SHOT AFTER 10:00? ⚽️ (EXCLUDING BLOCKED SHOTS)',
            active: false,
            autoTakeDown: null,
            display: true,
            displayOrder: 466,
            tradedInPlay: true,
            forecastsOffered: null,
            tricastsOffered: null,
            inPlayDelaySettings: null,
            sp: false,
            line: null,
            asianInPlayLine: null,
            cashoutAvailable: true,
            outright: false,
            bp: false,
            bpApplicable: false,
            spApplicable: false,
            spOnly: false,
            eachWayStakeReduction: null,
            betReferralEnabled: null,
            time: null,
            team: null,
            selections: {
                '34745295': {
                    id: 34745295,
                    name: 'NUJ',
                    nameWithoutLine: null,
                    active: false,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 1.85,
                        f: '17/20',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['N'],
                        'price-boost': ['no'],
                        'selection-identifier': ['N'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'kerosports-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: null,
                    asianInPlayLine: null,
                    nameWithPlaceholders: null,
                },
                '34745296': {
                    id: 34745296,
                    name: 'CCM',
                    nameWithoutLine: null,
                    active: false,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 1.85,
                        f: '17/20',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['Y'],
                        'price-boost': ['no'],
                        'selection-identifier': ['Y'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'kerosports-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: null,
                    asianInPlayLine: null,
                    nameWithPlaceholders: null,
                },
            },
            suspendTime: null,
            event: {
                id: 27072,
                name: 'Newcastle Jets vs Central Coast Mariners',
            },
            speedBetContext: {
                constraint: 'EXCLUDING BLOCKED SHOTS',
                contextNote: '0 shots for NUJ + CCM',
                isCore: false,
                timestamp: 1732267481660,
                translations: {},
            },
            template: {
                id: 'kerosports-1',
                eventTemplateId: 'match',
                customName: 'Fast Markets',
                sportId: 'football',
                name: 'Fast Markets (1)',
                marketTemplateType: 'kerosports-1',
                mainGroup: null,
                period: null,
                marketTypeGeneric: 'yesno',
            },
            eachWay: null,
            tags: {
                'market-display': ['-'],
                'market-group--popular-markets': ['no'],
                'website-main': ['no'],
                'asian-view': ['no'],
                'build-a-bet': ['no'],
                'market-group': ['Fast Markets'],
                'display-template': ['-'],
                outright: ['no'],
                'ante-post': ['no'],
                'display-order': ['-'],
                'website-popular': ['-'],
            },
            revision: 0,
        },
        {
            id: 12804697,
            name: 'NO SHOTS BY EITHER TEAM SO FAR. WHICH TEAM WILL TAKE THE FIRST SHOT AFTER 11:00? ⚽️ (EXCLUDING BLOCKED SHOTS)',
            active: true,
            autoTakeDown: null,
            display: true,
            displayOrder: 466,
            tradedInPlay: true,
            forecastsOffered: null,
            tricastsOffered: null,
            inPlayDelaySettings: null,
            sp: false,
            line: null,
            asianInPlayLine: null,
            cashoutAvailable: true,
            outright: false,
            bp: false,
            bpApplicable: false,
            spApplicable: false,
            spOnly: false,
            eachWayStakeReduction: null,
            betReferralEnabled: null,
            time: null,
            team: null,
            selections: {
                '34744971': {
                    id: 34744971,
                    name: 'NUJ',
                    nameWithoutLine: null,
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 1.85,
                        f: '17/20',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['N'],
                        'price-boost': ['no'],
                        'selection-identifier': ['N'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'kerosports-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: null,
                    asianInPlayLine: null,
                    nameWithPlaceholders: null,
                },
                '34744972': {
                    id: 34744972,
                    name: 'CCM',
                    nameWithoutLine: null,
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 1.85,
                        f: '17/20',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['Y'],
                        'price-boost': ['no'],
                        'selection-identifier': ['Y'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'kerosports-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: null,
                    asianInPlayLine: null,
                    nameWithPlaceholders: null,
                },
            },
            suspendTime: null,
            event: {
                id: 27072,
                name: 'Newcastle Jets vs Central Coast Mariners',
            },
            speedBetContext: {
                constraint: 'EXCLUDING BLOCKED SHOTS',
                contextNote: '0 shots for NUJ + CCM',
                isCore: false,
                timestamp: 1732267436140,
                translations: {},
            },
            template: {
                id: 'kerosports-1',
                eventTemplateId: 'match',
                customName: 'Fast Markets',
                sportId: 'football',
                name: 'Fast Markets (1)',
                marketTemplateType: 'kerosports-1',
                mainGroup: null,
                period: null,
                marketTypeGeneric: 'yesno',
            },
            eachWay: null,
            tags: {
                'market-display': ['-'],
                'market-group--popular-markets': ['no'],
                'website-main': ['no'],
                'asian-view': ['no'],
                'build-a-bet': ['no'],
                'market-group': ['Fast Markets'],
                'display-template': ['-'],
                outright: ['no'],
                'ante-post': ['no'],
                'display-order': ['-'],
                'website-popular': ['-'],
            },
            revision: 0,
        },
        {
            id: 12805297,
            name: 'NO SHOTS BY EITHER TEAM SO FAR. WHICH TEAM WILL TAKE THE FIRST SHOT AFTER 12:00? ⚽️ (EXCLUDING BLOCKED SHOTS)',
            active: true,
            autoTakeDown: null,
            display: true,
            displayOrder: 466,
            tradedInPlay: true,
            forecastsOffered: null,
            tricastsOffered: null,
            inPlayDelaySettings: null,
            sp: false,
            line: null,
            asianInPlayLine: null,
            cashoutAvailable: true,
            outright: false,
            bp: false,
            bpApplicable: false,
            spApplicable: false,
            spOnly: false,
            eachWayStakeReduction: null,
            betReferralEnabled: null,
            time: null,
            team: null,
            selections: {
                '34744971': {
                    id: 34744971,
                    name: 'NUJ',
                    nameWithoutLine: null,
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 1.85,
                        f: '17/20',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['N'],
                        'price-boost': ['no'],
                        'selection-identifier': ['N'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'kerosports-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: null,
                    asianInPlayLine: null,
                    nameWithPlaceholders: null,
                },
                '34744972': {
                    id: 34744972,
                    name: 'CCM',
                    nameWithoutLine: null,
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 1.85,
                        f: '17/20',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['Y'],
                        'price-boost': ['no'],
                        'selection-identifier': ['Y'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'kerosports-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: null,
                    asianInPlayLine: null,
                    nameWithPlaceholders: null,
                },
            },
            suspendTime: null,
            event: {
                id: 27072,
                name: 'Newcastle Jets vs Central Coast Mariners',
            },
            speedBetContext: {
                constraint: 'EXCLUDING BLOCKED SHOTS',
                contextNote: '0 shots for NUJ + CCM',
                isCore: false,
                timestamp: 1732267436140,
                translations: {},
            },
            template: {
                id: 'kerosports-1',
                eventTemplateId: 'match',
                customName: 'Fast Markets',
                sportId: 'football',
                name: 'Fast Markets (1)',
                marketTemplateType: 'kerosports-1',
                mainGroup: null,
                period: null,
                marketTypeGeneric: 'yesno',
            },
            eachWay: null,
            tags: {
                'market-display': ['-'],
                'market-group--popular-markets': ['no'],
                'website-main': ['no'],
                'asian-view': ['no'],
                'build-a-bet': ['no'],
                'market-group': ['Fast Markets'],
                'display-template': ['-'],
                outright: ['no'],
                'ante-post': ['no'],
                'display-order': ['-'],
                'website-popular': ['-'],
            },
            revision: 0,
        },
        {
            id: 12805298,
            name: 'NO SHOTS BY EITHER TEAM SO FAR. WHICH TEAM WILL TAKE THE FIRST SHOT AFTER 12:20? ⚽️ (EXCLUDING BLOCKED SHOTS)',
            active: true,
            autoTakeDown: null,
            display: true,
            displayOrder: 466,
            tradedInPlay: true,
            forecastsOffered: null,
            tricastsOffered: null,
            inPlayDelaySettings: null,
            sp: false,
            line: null,
            asianInPlayLine: null,
            cashoutAvailable: true,
            outright: false,
            bp: false,
            bpApplicable: false,
            spApplicable: false,
            spOnly: false,
            eachWayStakeReduction: null,
            betReferralEnabled: null,
            time: null,
            team: null,
            selections: {
                '34744971': {
                    id: 34744971,
                    name: 'NUJ',
                    nameWithoutLine: null,
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 1.95,
                        f: '17/20',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['N'],
                        'price-boost': ['no'],
                        'selection-identifier': ['N'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'kerosports-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: null,
                    asianInPlayLine: null,
                    nameWithPlaceholders: null,
                },
                '34744972': {
                    id: 34744972,
                    name: 'CCM',
                    nameWithoutLine: null,
                    active: true,
                    display: true,
                    displayOrder: 0,
                    price: {
                        d: 1.95,
                        f: '17/20',
                    },
                    state: 'open',
                    tags: {
                        'selection-identifiers--football': ['Y'],
                        'price-boost': ['no'],
                        'selection-identifier': ['Y'],
                    },
                    template: {
                        id: 'default-selection',
                        marketTemplateId: 'kerosports-1',
                        eventTemplateId: 'match',
                        sportId: 'football',
                        name: 'default-selection',
                    },
                    line: null,
                    asianInPlayLine: null,
                    nameWithPlaceholders: null,
                },
            },
            suspendTime: null,
            event: {
                id: 27072,
                name: 'Newcastle Jets vs Central Coast Mariners',
            },
            speedBetContext: {
                constraint: 'EXCLUDING BLOCKED SHOTS',
                contextNote: '0 shots for NUJ + CCM',
                isCore: false,
                timestamp: 1732267436140,
                translations: {},
            },
            template: {
                id: 'kerosports-1',
                eventTemplateId: 'match',
                customName: 'Fast Markets',
                sportId: 'football',
                name: 'Fast Markets (1)',
                marketTemplateType: 'kerosports-1',
                mainGroup: null,
                period: null,
                marketTypeGeneric: 'yesno',
            },
            eachWay: null,
            tags: {
                'market-display': ['-'],
                'market-group--popular-markets': ['no'],
                'website-main': ['no'],
                'asian-view': ['no'],
                'build-a-bet': ['no'],
                'market-group': ['Fast Markets'],
                'display-template': ['-'],
                outright: ['no'],
                'ante-post': ['no'],
                'display-order': ['-'],
                'website-popular': ['-'],
            },
            revision: 0,
        },
    ],
} as unknown as SpeedBetMarkets;

export const mockedMarkets = [
    {
        id: 18012,
        name: '1 FC MISSED A SHOT! WILL THEI NEXT SHOT AFTE 4:00 MISS THE TAGET AS WELL? ??',
        active: true,
        autoTakeDown: null,
        display: true,
        displayOrder: 99999,
        tradedInPlay: true,
        forecastsOffered: null,
        tricastsOffered: null,
        inPlayDelaySettings: null,
        sp: false,
        line: null,
        asianInPlayLine: null,
        cashoutAvailable: true,
        outright: false,
        bp: false,
        bpApplicable: false,
        spApplicable: false,
        spOnly: false,
        eachWayStakeReduction: null,
        betReferralEnabled: null,
        time: null,
        team: null,
        selections: {
            '56185': {
                id: 56185,
                name: '아니요',
                nameWithoutLine: null,
                active: true,
                display: true,
                displayOrder: 0,
                price: {
                    d: 1.82,
                    f: '41/50',
                },
                state: 'open',
                tags: {
                    'selection-identifiers--basketball': ['N'],
                    'price-boost': ['no'],
                    'selection-identifier': ['N'],
                },
                template: {
                    id: 'default-selection',
                    marketTemplateId: 'kerosports-1',
                    eventTemplateId: 'multi-participant-event',
                    sportId: 'basketball',
                    name: 'default-selection',
                },
                line: null,
                asianInPlayLine: null,
                nameWithPlaceholders: null,
            },
            '56186': {
                id: 56186,
                name: '예',
                nameWithoutLine: null,
                active: true,
                display: true,
                displayOrder: 0,
                price: {
                    d: 1.79,
                    f: '79/100',
                },
                state: 'open',
                tags: {
                    'selection-identifiers--basketball': ['Y'],
                    'price-boost': ['no'],
                    'selection-identifier': ['Y'],
                },
                template: {
                    id: 'default-selection',
                    marketTemplateId: 'kerosports-1',
                    eventTemplateId: 'multi-participant-event',
                    sportId: 'basketball',
                    name: 'default-selection',
                },
                line: null,
                asianInPlayLine: null,
                nameWithPlaceholders: null,
            },
        },
        suspendTime: null,
        event: {
            id: 249,
            name: 'Szolnoki Olaj Kk vs Ose Lions',
        },
        speedBetContext: {
            constraint: 'EXCLUDING BLOCKED SHOTS',
            contextNote: 'FC has 1 shot off target',
            isCore: true,
            timestamp: 1009,
        },
        template: {
            id: 'kerosports-1',
            eventTemplateId: 'multi-participant-event',
            customName: 'Fast Markets',
            sportId: 'basketball',
            name: 'Fast Markets (1)',
            marketTemplateType: 'kerosports-1',
            mainGroup: null,
            period: null,
            marketTypeGeneric: 'yesno',
        },
        eachWay: null,
        tags: {
            'market-display': ['-'],
            'market-group--popular-markets': ['no'],
            'website-main': ['no'],
            'asian-view': ['no'],
            'build-a-bet': ['no'],
            'market-group': ['Fast Markets'],
            'display-template': ['-'],
            outright: ['no'],
            'ante-post': ['no'],
            'display-order': ['-'],
            'website-popular': ['-'],
        },
        revision: 1,
    },
    {
        id: 51367,
        name: '2 FC MISSED A SHOT! WILL THEI NEXT SHOT AFTE 4:00 MISS THE TAGET AS WELL? ??: EXCLUDING BLOCKED SHOTS',
        active: true,
        autoTakeDown: null,
        display: true,
        displayOrder: 99999,
        tradedInPlay: true,
        forecastsOffered: null,
        tricastsOffered: null,
        inPlayDelaySettings: null,
        sp: false,
        line: null,
        asianInPlayLine: null,
        cashoutAvailable: true,
        outright: false,
        bp: false,
        bpApplicable: false,
        spApplicable: false,
        spOnly: false,
        eachWayStakeReduction: null,
        betReferralEnabled: null,
        time: null,
        team: null,
        selections: {
            '160017': {
                id: 160017,
                name: '아니요',
                nameWithoutLine: null,
                active: true,
                display: true,
                displayOrder: 0,
                price: {
                    d: 1.91,
                    f: '41/50',
                },
                state: 'open',
                tags: {
                    'selection-identifiers--basketball': ['N'],
                    'price-boost': ['no'],
                    'selection-identifier': ['N'],
                },
                template: {
                    id: 'default-selection',
                    marketTemplateId: 'kerosports-1',
                    eventTemplateId: 'multi-participant-event',
                    sportId: 'basketball',
                    name: 'default-selection',
                },
                line: null,
                asianInPlayLine: null,
                nameWithPlaceholders: null,
            },
            '160018': {
                id: 160018,
                name: '예',
                nameWithoutLine: null,
                active: true,
                display: true,
                displayOrder: 0,
                price: {
                    d: 1.02,
                    f: '79/100',
                },
                state: 'open',
                tags: {
                    'selection-identifiers--basketball': ['Y'],
                    'price-boost': ['no'],
                    'selection-identifier': ['Y'],
                },
                template: {
                    id: 'default-selection',
                    marketTemplateId: 'kerosports-1',
                    eventTemplateId: 'multi-participant-event',
                    sportId: 'basketball',
                    name: 'default-selection',
                },
                line: null,
                asianInPlayLine: null,
                nameWithPlaceholders: null,
            },
        },
        suspendTime: null,
        event: {
            id: 249,
            name: 'Szolnoki Olaj Kk vs Ose Lions',
        },
        speedBetContext: {
            constraint: 'EXCLUDING BLOCKED SHOTS',
            contextNote: 'FC has 1 shot off target',
            isCore: true,
            timestamp: 1009,
        },
        template: {
            id: 'kerosports-1',
            eventTemplateId: 'multi-participant-event',
            customName: 'Fast Markets',
            sportId: 'basketball',
            name: 'Fast Markets (1)',
            marketTemplateType: 'kerosports-1',
            mainGroup: null,
            period: null,
            marketTypeGeneric: 'yesno',
        },
        eachWay: null,
        tags: {
            'market-display': ['-'],
            'market-group--popular-markets': ['no'],
            'website-main': ['no'],
            'asian-view': ['no'],
            'build-a-bet': ['no'],
            'market-group': ['Fast Markets'],
            'display-template': ['-'],
            outright: ['no'],
            'ante-post': ['no'],
            'display-order': ['-'],
            'website-popular': ['-'],
        },
        revision: 0,
    },
    {
        id: 51824,
        name: '3 FC MISSED A SHOT! WILL THEI NEXT SHOT AFTE 4:00 MISS THE TAGET AS WELL? ??: EXCLUDING BLOCKED SHOTS; EXCLUDING BLOCKED SHOTS 2',
        active: true,
        autoTakeDown: null,
        display: true,
        displayOrder: 99999,
        tradedInPlay: true,
        forecastsOffered: null,
        tricastsOffered: null,
        inPlayDelaySettings: null,
        sp: false,
        line: null,
        asianInPlayLine: null,
        cashoutAvailable: true,
        outright: false,
        bp: false,
        bpApplicable: false,
        spApplicable: false,
        spOnly: false,
        eachWayStakeReduction: null,
        betReferralEnabled: null,
        time: null,
        team: null,
        selections: {
            '161403': {
                id: 161403,
                name: '아니요',
                nameWithoutLine: null,
                active: true,
                display: true,
                displayOrder: 0,
                price: {
                    d: 1.01,
                    f: '41/50',
                },
                state: 'open',
                tags: {
                    'selection-identifiers--basketball': ['N'],
                    'price-boost': ['no'],
                    'selection-identifier': ['N'],
                },
                template: {
                    id: 'default-selection',
                    marketTemplateId: 'kerosports-1',
                    eventTemplateId: 'multi-participant-event',
                    sportId: 'basketball',
                    name: 'default-selection',
                },
                line: null,
                asianInPlayLine: null,
                nameWithPlaceholders: null,
            },
            '161404': {
                id: 161404,
                name: '예',
                nameWithoutLine: null,
                active: true,
                display: true,
                displayOrder: 0,
                price: {
                    d: 1.99,
                    f: '79/100',
                },
                state: 'open',
                tags: {
                    'selection-identifiers--basketball': ['Y'],
                    'price-boost': ['no'],
                    'selection-identifier': ['Y'],
                },
                template: {
                    id: 'default-selection',
                    marketTemplateId: 'kerosports-1',
                    eventTemplateId: 'multi-participant-event',
                    sportId: 'basketball',
                    name: 'default-selection',
                },
                line: null,
                asianInPlayLine: null,
                nameWithPlaceholders: null,
            },
        },
        suspendTime: null,
        event: {
            id: 249,
            name: 'Szolnoki Olaj Kk vs Ose Lions',
        },
        speedBetContext: {
            constraint: 'EXCLUDING BLOCKED SHOTS',
            contextNote: 'FC has 1 shot off target',
            isCore: true,
            timestamp: 1009,
        },
        template: {
            id: 'kerosports-1',
            eventTemplateId: 'multi-participant-event',
            customName: 'Fast Markets',
            sportId: 'basketball',
            name: 'Fast Markets (1)',
            marketTemplateType: 'kerosports-1',
            mainGroup: null,
            period: null,
            marketTypeGeneric: 'yesno',
        },
        eachWay: null,
        tags: {
            'market-display': ['-'],
            'market-group--popular-markets': ['no'],
            'website-main': ['no'],
            'asian-view': ['no'],
            'build-a-bet': ['no'],
            'market-group': ['Fast Markets'],
            'display-template': ['-'],
            outright: ['no'],
            'ante-post': ['no'],
            'display-order': ['-'],
            'website-popular': ['-'],
        },
        revision: 0,
    },
    {
        id: 51829,
        name: '3 FC MISSED A SHOT! WILL THEI NEXT SHOT AFTE 4:00 MISS THE TAGET AS WELL? ??: EXCLUDING BLOCKED SHOTS; EXCLUDING BLOCKED SHOTS 2',
        active: true,
        autoTakeDown: null,
        display: true,
        displayOrder: 99999,
        tradedInPlay: true,
        forecastsOffered: null,
        tricastsOffered: null,
        inPlayDelaySettings: null,
        sp: false,
        line: null,
        asianInPlayLine: null,
        cashoutAvailable: true,
        outright: false,
        bp: false,
        bpApplicable: false,
        spApplicable: false,
        spOnly: false,
        eachWayStakeReduction: null,
        betReferralEnabled: null,
        time: null,
        team: null,
        selections: {
            '161403': {
                id: 161403,
                name: '아니요',
                nameWithoutLine: null,
                active: true,
                display: true,
                displayOrder: 0,
                price: {
                    d: 1.01,
                    f: '41/50',
                },
                state: 'open',
                tags: {
                    'selection-identifiers--basketball': ['N'],
                    'price-boost': ['no'],
                    'selection-identifier': ['N'],
                },
                template: {
                    id: 'default-selection',
                    marketTemplateId: 'kerosports-1',
                    eventTemplateId: 'multi-participant-event',
                    sportId: 'basketball',
                    name: 'default-selection',
                },
                line: null,
                asianInPlayLine: null,
                nameWithPlaceholders: null,
            },
            '161404': {
                id: 161404,
                name: '예',
                nameWithoutLine: null,
                active: true,
                display: true,
                displayOrder: 0,
                price: {
                    d: 1.99,
                    f: '79/100',
                },
                state: 'open',
                tags: {
                    'selection-identifiers--basketball': ['Y'],
                    'price-boost': ['no'],
                    'selection-identifier': ['Y'],
                },
                template: {
                    id: 'default-selection',
                    marketTemplateId: 'kerosports-1',
                    eventTemplateId: 'multi-participant-event',
                    sportId: 'basketball',
                    name: 'default-selection',
                },
                line: null,
                asianInPlayLine: null,
                nameWithPlaceholders: null,
            },
        },
        suspendTime: null,
        event: {
            id: 249,
            name: 'Szolnoki Olaj Kk vs Ose Lions',
        },
        speedBetContext: {
            constraint: 'EXCLUDING BLOCKED SHOTS',
            contextNote: 'FC has 1 shot off target',
            isCore: true,
            timestamp: 1009,
        },
        template: {
            id: 'kerosports-1',
            eventTemplateId: 'multi-participant-event',
            customName: 'Fast Markets',
            sportId: 'basketball',
            name: 'Fast Markets (1)',
            marketTemplateType: 'kerosports-1',
            mainGroup: null,
            period: null,
            marketTypeGeneric: 'yesno',
        },
        eachWay: null,
        tags: {
            'market-display': ['-'],
            'market-group--popular-markets': ['no'],
            'website-main': ['no'],
            'asian-view': ['no'],
            'build-a-bet': ['no'],
            'market-group': ['Fast Markets'],
            'display-template': ['-'],
            outright: ['no'],
            'ante-post': ['no'],
            'display-order': ['-'],
            'website-popular': ['-'],
        },
        revision: 0,
    },
];
