export const mockMarket = {
    id: 40611,
    name: 'Winner',
    active: true,
    autoTakeDown: null,
    display: true,
    displayOrder: 1,
    tradedInPlay: false,
    forecastsOffered: null,
    tricastsOffered: null,
    inPlayDelaySettings: null,
    sp: false,
    line: null,
    cashoutAvailable: true,
    outright: false,
    bp: null,
    bpApplicable: null,
    spApplicable: null,
    spOnly: false,
    eachWayStakeReduction: null,
    betReferralEnabled: null,
    time: null,
    team: null,
    selections: [124989, 124990],
    suspendTime: null,
    event: {
        id: 1060,
        name: 'Bks Bielsko-Biala vs Budowlani Lodz',
    },
    template: {
        id: 'bet-radar-186',
        eventTemplateId: 'multi-participant-event',
        customName: null,
        sportId: 'volleyball',
        name: 'Winner (186)',
        marketTemplateType: '186',
        mainGroup: null,
        period: 'Regular play',
        marketTypeGeneric: 'twowaywinner',
    },
    eachWay: null,
    tags: {
        'market-display': ['-'],
        'market-group--popular-markets': ['no'],
        'website-main': ['yes'],
        'asian-view': ['yes'],
        'build-a-bet': ['no'],
        'market-group': ['Main'],
        'display-template': ['-'],
        outright: ['no'],
        'ante-post': ['no'],
        'display-order': ['-'],
        'website-popular': ['-'],
    },
    revision: 11,
};

export const mockSelection = {
    id: 124989,
    name: 'Bks Bielsko-Biala',
    active: true,
    display: true,
    displayOrder: 0,
    price: {
        d: 1.47,
        f: '47/100',
    },
    state: 'open',
    tags: {
        'price-boost': ['no'],
        'selection-identifier': ['H'],
        'selection-identifiers--volleyball': ['H'],
    },
    template: {
        id: 'default-selection',
        marketTemplateId: 'bet-radar-186',
        eventTemplateId: 'multi-participant-event',
        sportId: 'volleyball',
        name: 'default-selection',
    },
    metadata: {
        silk: null,
        silkUrl: null,
        number: null,
        weight: null,
        drawn: null,
        jockey: null,
        trainer: null,
        status: null,
        place: null,
    },
};
